### ISSUE TITLE
format and lint:fix format code differently

### ISSUE THREAD

**Issue by allen-ziegenfus** [liferay/liferay-frontend-projects#1084]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x ] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Description

**Desired behavior:**

lint:fix and format should format code consistently. 

**Current behavior:**

format removes space between sibling html nodes, lint:fix adds space

**Repro instructions (if applicable):**

Run format and lint:fix on this file - the two formatting runs give different results - I believe lint:fix is the correct one

https://github.com/liferay/liferay-portal/blob/master/workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-custom-element/src/pages/LoadingPage/LoadingPage.tsx#L24-L28

**Other information (environment, versions etc):**

**Comment by bryceosterhaus** [comment]
Hey @allen-ziegenfus, do to the nature of each tool(eslint and prettier), they actually aren't gonna be consistent with one another, which is why we run one after the other. Prettier handles the majority of formatting issues and then eslint is used for more nit-picky structure of the code, such as making sure a variable is declared before it is used.

I believe the correct order is `lint:fix` and then `format`, as that is [what we do in npm-scripts](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/npm-tools/packages/npm-scripts/src/scripts/fix.js#L12).

So I think that file is formatted correctly. I also vaguely remember there being an odd edge case for our rules with that trailing `{' '}`, so maybe you are running into an issue with that specifically. I think the issue was that we couldn't auto-fix new lines after a literal space for some reason.

Gonna close since this is expected, but we can continue the conversation here
