### ISSUE TITLE
Unable to debug React JS widget with code not minified

### ISSUE THREAD

**Issue by luizfmarins** [liferay/liferay-frontend-projects#1096]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [X] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :two: v2.x
-   [ ] :three: v3.x
Not sure which vesion.
I'm using com.liferay.gradle.plugins.workspace 4.0.24 to build it.

### Description

**Desired behavior:**
During development, I should be able to deploy a React JS widget on Chrome using the non minified code.

**Current behavior:**
I can debug using only the minified code

**Repro instructions (if applicable):**

1. Create a new react widget using liferay new try-debug
2. Setting NODE_ENV to development: export NODE_ENV=development
3. Using portal-developer.properties: include-and-override=portal-developer.properties
4. Deploy the widget to a Liferay 7.4 U54. Add to the page.
Result:
![image (1)](https://user-images.githubusercontent.com/4074831/222500102-37f8291e-10f9-4bb0-a546-585e266892fd.png)

**Other information (environment, versions etc):**
Liferay 7.4 U54
com.liferay.gradle.plugins.workspace = 4.0.24
Sample project: [try-debug-fe.tar.gz](https://github.com/liferay/liferay-frontend-projects/files/10873915/try-debug-fe.tar.gz)
Slack thread: https://liferay.slack.com/archives/C03CAD9EF/p1677710229122429?thread_ts=1656002160.024079&cid=C03CAD9EF
Support ticket: https://liferay-support.zendesk.com/agent/tickets/82508

**Comment by izaera** [comment]
Mmm, don't know why, I thought this was related to a custom element CE, but it's not, of course. It's an AMD portlet. Source maps should work for custom element CEs.

Now, regarding AMD portlets, IINM, full-blown source maps have never been supported for this type of project... 

Specifically, source maps will always be problematic in any AMD build because we wrap code built with a previous tool (babel, typescript, ...), that has already generated a source map, with `Liferay.Loader.define`, which "breaks" the source map unless we rewrite it.

Additionally, modifying a source map after it's generated is quite difficult so I think we never implemented it, but I wouldn't swear for it. I need to check in depth the source code, because I don't remember.

Can you confirm if you have seen this working before? 🤔 Thanks.

The reason why I'm doubt is because adding a single line, like `Liferay.Loader.define` may make rewriting the source map feasible since it is a simple offset from the original one, thus I'm not sure if we did that in the past or not, finally. I will check the source code of npm-bundler, but having a confirmation would be quite useful.

**Comment by izaera** [comment]
According to liferay-npm-bundler report file, this is all we run when transforming a .js file:

![image](https://user-images.githubusercontent.com/3273630/222713425-9753da6d-69f0-4928-9953-599177ac17b7.png)

I can't see any place where we tweak the source maps generated by Babel, which makes me suspect this has never worked as requested...

I'm going to check each phase internally.

**Comment by izaera** [comment]
Yep, this is what should make the magic happen -> https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/steps/transform.js#L210

Now we only need to know why it doesn't... :-/

**Comment by izaera** [comment]
Apparently the first babel phase is not generating source maps.

**Comment by luizfmarins** [comment]
Hi Ivan,

> Can you confirm if you have seen this working before?
This is the first project I'm using [@liferay/cli](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-toolkit/docs/manuals/liferay-cli.md?plain=1#L49).
In my previous projects with Liferay 7.1 and 7.2 it used to work, but we were using the `liferay-npm-bundler`.

**Comment by izaera** [comment]
Yeah, I think this was broken with `@liferay/cli` for some reason...

**Comment by izaera** [comment]
I think [this](https://github.com/liferay/liferay-frontend-projects/pull/1097) fixes it.

**Comment by izaera** [comment]
This release https://github.com/liferay/liferay-frontend-projects/releases/tag/portal-base%2Fv1.6.1 should fix the problem.

**Comment by luizfmarins** [comment]
Hi Ivan,

I tested it and it works now.
![image](https://user-images.githubusercontent.com/4074831/223162666-e4e6b129-d070-4c4c-8281-28009bdf2227.png)
Thank you very much.

**Comment by izaera** [comment]
![clap](https://media.giphy.com/media/mPOGx4hJtOWSA/giphy.gif)
