### ISSUE TITLE
Require a scope when pushing semantic commits

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#125]
This originates in this [private Slack conversation](https://liferay.slack.com/archives/G3JBR21HA/p1601971888245700).

Now that we have all projects into one single repo, it would be great (if not necessary) to be able to distinguish commits by (at least) project. Otherwise, filtering mail notifications, browsing git's history, and similar tasks can be a nightmare.

So, the proposed solution is to leverage the [semantic versioning bot](https://github.com/zeke/semantic-pull-requests) to enforce that.

**Comment by wincent** [comment]
I foresee a future in which we implement our own bot... Because [this issue](https://github.com/zeke/semantic-pull-requests/issues/82) suggests that scope enforcement _might_ not work, and in any case, based on the docs, I suspect that the bot is supposed to reject invalid scopes but I don't see anything in there about it _requiring_ scopes.

This might be one of those things where we just get better with practice, because even if we have the bot, you'll still get the notification when somebody sends a "bad" PR. But anyway, let's see how far we can get with this approach in the meantime.

**Comment by wincent** [comment]
Looking at [this line](https://github.com/zeke/semantic-pull-requests/blob/a1d743d558e012952f4d3ab395137487b32afe6e/lib/is-semantic-message.js#L20), I'd say we can check valid scopes, but it is not going to complain about absence of a scope.

So I created a feature request: https://github.com/zeke/semantic-pull-requests/issues/119

**Comment by izaera** [comment]
I'm going to close this since it seems we haven't needed it for a long time :shrug:
