### ISSUE TITLE
ES6 dependencies are not compiled

### ISSUE THREAD

**Issue by sashafirsov** [liferay/liferay-frontend-projects#165]
Upon generating the JS based portlet with `yo liferay-bundle` and adding "@vaadin/vaadin-upload" npm dependency, the browser gives an error 'Uncaught SyntaxError: Unexpected string' on generated code
```javascript
Liferay.Loader.define('@js-based-portlet$vaadin/vaadin-upload@4.2.1/vaadin-upload', ['module', 'exports', 'require'], function (module, exports, require) {
  var define = undefined;
  import './theme/lumo/vaadin-upload.js';
});
```
On line 3 the static 'import' definitely is a wrong syntax. 

The source of error is in vaadin-upload dependency taken from node_modules. Which instead of been compiled with Babel, had been injected without processing. As you can guess the file comprise just one line
```javascript
import './theme/lumo/vaadin-upload.js';
```
The `liferay-npm-bundler` does not use .babelrc 'env' preset which is used for compiling the sources but not for dependencies. 

Unfortunately I was not able to locate any doc which will guide to tune up `liferay-npm-bundler` with another preset than default, meaning not able to trigger compilation of ES6 module dependencies.

**Comment by wincent** [comment]
Given [this comment](https://github.com/liferay/liferay-frontend-projects/issues/165#issuecomment-617720804), sticking the 3.x label on this one.

**Comment by faragos** [comment]
Because this issue is similiar to my problem, I will write it here, but the solution would be the same:
I tried to use recoil.js as a state management. They use ES6 with the spread-operator in their npm-package. The Liferay-bundler can't handle those, because it isn't ES5. This way the whole package doesn't get wrapped and can't be loaded.
At the moment, I didn't find a way how I can modify the .babelrc, that allows it to transpile the dependencies with spread-operators in it.

![es6-fail](https://user-images.githubusercontent.com/10152106/120431350-a7953f00-c378-11eb-9b05-dca794d6755e.png)

**Comment by izaera** [comment]
> but the solution would be the same

@faragos :thinking: Not sure... This issue is about transpiling deps in `node_modules` from ES6 to ES5, something the bundler cannot do unless -maybe- using rules and a babel loader, though I haven't tried and I'm not sure if it would work, off the top of my head. I think that's what you tried @faragos, but didn't work... (:one: )

A different thing would be understanding the spread operator to be able to wrap the module, but leaving it untouched (so no transpiling would be done and the target browser would need to know how to handle the spread operator). (:two: )

So, what would be your case? :one: or :two: ? Depending on the scenario you are the solution is completely different, being :two: the easiest one to fix (probably).

**Comment by faragos** [comment]
@izaera hmm true. I only thought about solution 1️⃣ . But yeah you are right I think an easier and cleaner way would be 2️⃣ . Should I write a new ticket then? :)

**Comment by izaera** [comment]
> Should I write a new ticket then? :)

If it is :two: yes, please :+1: so that I can have a look when I get what I'm doing now to a stable state :roll_eyes:
