### ISSUE TITLE
Too many modules fetched with Angular makes resolution very slow

### ISSUE THREAD

**Issue by wsyski** [liferay/liferay-frontend-projects#170]
I am reopening this only because you have offered some guidance in your previous answer. I was also thinking about building a kind of angular runtime with webpack (ex. using webpack.DllPlugin as in https://github.com/xtivia/jetray-runtime-angular, but I did not know how to integrate this with liferay npm bundler. Was it the approach you are suggesting? I would welcome your guidance. Do you have a working example? Thanks in advance.

_Originally posted by @wsyski in https://github.com/liferay/liferay-js-toolkit/issues/457#issuecomment-558582844_

**Comment by wincent** [comment]
Given [this comment](https://github.com/liferay/liferay-frontend-projects/issues/170#issuecomment-630022409) I am going to close this one, but we can re-open it (or create another) if it comes up again. It is quite possible that this will cease to be an issue in the 3.x series because it's an entirely different architecture.
