### ISSUE TITLE
Can we debug adapted  portlets? Where is the map file?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-frontend-projects#172]
So if we are attempting to debug an adapted portlet, say one based on the Angular CLI, where does my code actually end up, so that i can find the source to insert breakpoints?

And can i even use the debugger at all on adapted portlets? I don't see any .map files being included in the generated jar for my application code

**Comment by wincent** [comment]
I'm adding the 3.x label to this based on my reading of the above (because, if this gets fixed, it will likely get fixed there first).

**Comment by izaera** [comment]
I'm removing the `3.x` label since, if this is done, it will only be done for v2 (as v3 is going to be based in webpack).

**Comment by mfreeman-xtivia** [comment]
So guys i have "lost the pea" on this a little bit...

Where did we end up on being able to use source maps for adapted portlets?

**Comment by izaera** [comment]
Sadly nowhere :-(. I did a PoC of sourcemap relocation in a test project, but the task is quite difficult for this case.

Basically, what I said in [this previous comment](https://github.com/liferay/liferay-frontend-projects/issues/172#issuecomment-685431026) remains valid.

CCing @dsanz and @david-truong so that they know we are missing this feature.

**Comment by izaera** [comment]
I really doubt we will be tackling this in the future, so I'm adding the `help-wanted` flag in case anyone from the community wants to contribute it and/or keep track on the interest in this feature.

**Comment by mfreeman-xtivia** [comment]
So what then is the recommended solution for debugging JS portlets in Liferay, other than console.log?
