### ISSUE TITLE
Webpack bundle URL is not including the public path for 3rd party compont.

### ISSUE THREAD

**Issue by rajadsms** [liferay/liferay-frontend-projects#185]
I have created a react portlet with generator-liferay-js in Liferay7.2.

In runtime this application making two webpack.bundle.js calls. The first one is by default which has the URL like http://localhost:8080/o/rotorCompTest/webpack.bundle.js which is working fine but the next call which is for third party component which I have included in portlet http://localhost:8080/12.webpack.bundle.js  is not working as it is not having the publicpath in the URL.

Ex:
The third-party component bundle file name is 12.webpack.bundle.js  and it is calling the URL  http://localhost:8080/12.webpack.bundle.js which is not including the public path.it should be http://localhost:8080/publicpath/12.webpack.bundle.js.

I googled the issue and found that I need to add publicPath property in output section of webpack.config.js file. But unable to update that file.This file is recreating every time.
Please help me.

**Comment by izaera** [comment]
> I googled the issue and found that I need to add publicPath property in output section of webpack.config.js file.

That won't help, because the adaptation process is calling webpack under the hood. This issue might have been caused due to the version of react not being supported. 

Since this issue is old I'm closing it as I assume it is fixed by now. However, if it keeps failing, please check again with the latest version of the JS Toolkit and reopen it so that we can analyze the issue properly. thx :-)
