### ISSUE TITLE
Please upgrade to Angular 10

### ISSUE THREAD

**Issue by creativeprogramming** [liferay/liferay-frontend-projects#192]
Please upgrade the liferay-js generator to use Angular 10

**Comment by wincent** [comment]
Just got pinged about this one on Slack to see whether there are any updates. This was last discussed in our team channel in [this thread](https://liferay.slack.com/archives/G3JBR21HA/p1604568690340200?thread_ts=1604568371.340100&cid=G3JBR21HA), about a month ago. Unfortunately I can't share the whole thing verbatim because it's from a private channel, but, paraphrasing, the basic discussion noted:

- We get occasional requests to update to newer versions.
- It's difficult to keep up with Angular's frequent releases _proactively_, because they do so many of them (and sometimes the updates are not easy), so we have typically let external demand drive prioritization decisions (ie. we don't generally update or test until somebody asks us to).
- Given that we have to deal with not only Angular but also React and Vue, this reactive policy has seemed the most pragmatic approach so far. As in, an informal policy of "always support the latest version, but without a well-defined SLA for how quickly we verify support when new versions come out and make any necessary changes".
- We discussed the possibility of tying version support to specific DXP releases. There are more and more of those each year (at the time of writing, live versions include 6.2, 7.0, 7.1, 7.2 and 7.3), and the versions of the JS toolkit in use vary by release. Because the technology stack has changed so dramatically over that interval, it is probably not realistic to expect that we'll ever/always be in a place where all non-EOL releases are using the same version of the toolkit. We have historically tried to maintain forwards and backwards compatibility with the toolkit, but we may not be able to do that forever (for example, see recent experimentation with webpack 5, which is effectively an entirely different architecture).

Anyway, given that discussion, @izaera was [going to do a test update to the latest Angular](https://liferay.slack.com/archives/G3JBR21HA/p1604586439368700?thread_ts=1604568371.340100&cid=G3JBR21HA) and report on the result, but I'm not sure what the final status of that was.

**Comment by izaera** [comment]
It's done now: https://github.com/liferay/liferay-frontend-projects/releases/tag/liferay-js-toolkit%2Fv2.20.0
