### ISSUE TITLE
lnbs-start serves css files as text/html

### ISSUE THREAD

**Issue by creativeprogramming** [liferay/liferay-frontend-projects#208]
Refused to apply style from 'http://localhost:8081/o/csndc-alerting-gui/node_modules/csndc-alerting-gui$primeng@10.0.3/resources/primeng.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
(index):1 Refused to apply style from 'http://localhost:8081/o/csndc-alerting-gui/node_modules/csndc-alerting-gui$primeng@10.0.3/resources/themes/nova/theme.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
(index):1 Refused to apply style from 'http://localhost:8081/o/csndc-alerting-gui/node_modules/csndc-alerting-gui$primeicons@4.0.0/primeicons.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by wincent** [comment]
I've seen messages like that when a resource I was requesting was 404-ing (ie. I was getting a "text/html" 404 error page instead of the thing I wanted). What are you getting when you request one of those files individually, in terms of headers and content @creativeprogramming?

Disclaimer: I don't actually know what lnbs-start is; I'm just somebody who works on some of the things in this repo.

**Comment by izaera** [comment]
The `lnbs-start` script launches a webpack development server to be able to do kind-of live development. However, because it only serves the `.js` part of the project, you are lacking all the Liferay DXP infrastructure so it is not the same environment. 

Think of it as the same difference when running a Cordova application in a browser versus running it in a mobile phone: you either have to write platform agnostic code or provide some way to shim mobile/browser behavior in the other platfom (browser/mobile).

In this case, your application is requesting a `.css` file from a URL starting with `/o/...`, which is a Liferay URL that webpack's development server won't understand. The only solution would be tweaking your build/application so that it detects where it is being run (`lnbs-start` or the true `Liferay DXP`) and requests the CSS from one place or the other.
