### ISSUE TITLE
Update Jest to 26.x for better API support

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-frontend-projects#231]
### Issue type (mark with `x`)

-   [x] :gift: Feature request

### Description

With our new support matrix for browsers, I think it would be helpful to update Jest to 26.x so that we can get better js-dom support. 

I was adding `document.createRange` and `createContextualFragment` and I realized that our current version of Jest does not support those APIs. I saw on [this issue](https://github.com/mui-org/material-ui/issues/15726#issuecomment-493124813) that `26.x` should now support those.

**Comment by wincent** [comment]
I think this is duplicate of https://github.com/liferay/liferay-frontend-projects/issues/46 — note that we have been holding off on the update due to [still-existing performance regressions introduced in Jest v25](https://github.com/facebook/jest/issues/9457). We actually did do an update at one point, although I don't have the link at hand, that was so bad that we had to roll it back (because the perf was so bad it made the tests time out).

**Comment by bryceosterhaus** [comment]
@wincent yep you're right, didn't see that one. Thanks!

**Comment by jbalsas** [comment]
One option would be to simply mock `createContextualFragment` with exactly what `metal-dom` does in `buildFragment`.

That way we can start using it and jest will know how to handle until we update it.

**Comment by wincent** [comment]
> One option would be to simply mock `createContextualFragment` with exactly what `metal-dom` does in `buildFragment`.

@bryceosterhaus did this in https://github.com/liferay/liferay-frontend-projects/pull/234

I made a note in https://github.com/liferay/liferay-frontend-projects/issues/46 reminding us to remove the mock once it's no longer needed.
