### ISSUE TITLE
Bring over liferay-r2 RTL package

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-projects#249]
As evidenced at [POC: dart sass for building css](https://github.com/liferay/liferay-frontend-projects/pull/245#pullrequestreview-535265795) we need to bring over the [liferay-labs/r2](https://github.com/liferay-labs/r2) project into `liferay-frontend-projects`. 

The project is currently only used inside the `liferay-js-themes-toolkit` but it should also be used within `liferay-npm-scripts` once we start handling sass compilation. We could decide not to even make it a public package but simply roll it locally into the ones that need it.

An alternative option to bringin that old fork here would be to try and find more up-to-date libraries such as [rtlcss](https://github.com/MohammadYounes/rtlcss) and evaluate their readiness...

**Comment by jbalsas** [comment]
Hey @bryceosterhaus, I'm assigning this to you too so we don't forget to get this done before moving any further after the Dart Sass integration!

**Comment by wincent** [comment]
Funnily enough, `liferay-js-themes-toolkit` uses [a copy-pasted version of it](https://github.com/liferay/liferay-js-themes-toolkit/blob/45ca23003efba9a23e1ea75fd736a00d57390961/packages/liferay-theme-tasks/lib/r2/index.js#L14) as far as I can tell. It was inlined [in this commit](https://github.com/liferay/liferay-js-themes-toolkit/commit/a843516ffb18bbeb9b3c3b1c7de8a2622d233b12#diff-a016e05e9164926c610083bf8d96c2a4d473221ecda45c00522bdef0c5d97585).

Some relevant discussion about [licensing in this thread](https://github.com/liferay/liferay-js-themes-toolkit/pull/424#discussion_r368860354) (although GitHub might hide it) — we need to be careful to preserve [the original third-party license](https://github.com/liferay-labs/R2/blob/a4551f5bd3b22f8c2f3d2df6f3f25baa300631dd/r2.js#L2-L5). We broke the rules a bit in the themes toolkit, mostly because I was conflict averse and didn't want to keep arguing about it. But let's do it properly this time.

In a sense moving it here is only solving half of the problem. Unless we un-inline it in `liferay-js-themes-toolkit`, we will have two divergent copies floating around in our graph. Maybe we should look at moving themes toolkit in here as well — the only reason I didn't move it in the initial burst of imports was that other work came up.

About actually moving this in here, with all the other imported projects, we [followed this procedure](https://github.com/liferay/liferay-frontend-projects/blob/master/CONTRIBUTING/importing-a-project.md) in order to, among other things, preserve history and tags etc. It would be nice if we could maintain that standard for this project too. Please let me know if you need any help with it @bryceosterhaus, especially the "fiddly bits" like subtree merge and tag rewriting.

**Comment by bryceosterhaus** [comment]
So it seems to make sense to bring in both `liferay-js-themes-toolkit` and `liferay-r2`. TBH, I'm not super confident in my git merge skills, so I might opt to let you(@wincent) handle those merges here. I am more than happy to attempt it, I just don't want to accidentally screw something up un-intentionally.

**Comment by wincent** [comment]
No problem, I can do it. We just need to decide the exact relationship that we want things to have here.

Currently we have:

-   `@liferay/npm-scripts` (in this repo): depends on `liferay-theme-tasks`, which, along the other `liferay-js-themes-toolkit` packages, is in a separate repo.
-   `liferay-theme-tasks`: includes a copy-pasted version of `liferay-r2`, which _was_ the only place that we were actually using `liferay-r2`, _until this PR_; specifically, right now:
    -   We have three more-to-less active branches in the `liferay-js-themes-toolkit` repo:
        -   `master`: corresponding to the v10.x series
        -   `9.x`
        -   `8.x`
    -   Of those branches, only `master` and `9.x` use copy pasted versions of `liferay-r2`.
    -   `8.x` consumes `liferay-r2` transitively, via a dependency on [`gulp-liferay-r2-css`](https://www.npmjs.com/package/gulp-liferay-r2-css), which is a package owned by Robert Frampton (no longer with Liferay) and hosted I have no idea where (closest I can find is [`gulp-r2-css` under his GitHub user](https://github.com/robframpton/gulp-r2-css), but that's not the same thing)... (this is why we should keep Liferay stuff in Liferay repos).

I think the desired end state might be:

- We import `liferay-theme-tasks` (and the other `liferay-js-themes-toolkit` packages) into this repo — only tricky part here is that we will want the `master` branch to go under `projects/` and the other two branches to get grafted under `maintenance/`.
- `@liferay/npm-scripts` continues to depend on `liferay-theme-tasks`, obviously.
- We tweak the scripts and theme tasks so that we can leverage the r2 functionality from the tasks in some way (I don't actually know exactly how yet, but I imagine it is just exposing it from the tasks package).
- (Optionally) We import `liferay-r2` into this repo to preserve its history, but we don't actually use it directly.

Required analysis to make sure we don't screw this up: double check to see how much divergence there was, if any, between the last `liferay-r2` release that we were using and what has been copy-pasted into the themes toolkit.

So it will probably be a bit fiddly, but I think we have to try to put our affairs in order or entropy will eventually overwhelm us. 😂

**Comment by izaera** [comment]
> Funnily enough, liferay-js-themes-toolkit uses a copy-pasted version of it as far as I can tell. It was inlined in this commit.

:-S Sorry about that. I read yesterday some comments about `liferay-r2` and knew that I inlined it, but didn't realized what the need was :-(. We inlined all that stuff some time ago when removing extra repositories.

**Comment by izaera** [comment]
Regarding the inlined version, I would use that one because, IIRC, I formatted and linted it a bit so that it met our expectations on the code...

**Comment by bryceosterhaus** [comment]
> - We import `liferay-theme-tasks` (and the other `liferay-js-themes-toolkit` packages) into this repo — only tricky part here is that we will want the `master` branch to go under `projects/` and the other two branches to get grafted under `maintenance/`.
> - `@liferay/npm-scripts` continues to depend on `liferay-theme-tasks`, obviously.
> - We tweak the scripts and theme tasks so that we can leverage the r2 functionality from the tasks in some way (I don't actually know exactly how yet, but I imagine it is just exposing it from the tasks package).

This sounds good to me. I like the idea of leveraging r2 from the theme tasks

**Comment by wincent** [comment]
Latest status is [described here](https://github.com/liferay/liferay-frontend-projects/pull/282/files#r543128702). Basically, we are set-up to do this trivially now, but I am just not clear on when/if we want to.

**Comment by wincent** [comment]
So as to not leave this hanging, exposing the API in https://github.com/liferay/liferay-frontend-projects/pull/301

**Comment by wincent** [comment]
Also sent https://github.com/liferay/liferay-frontend-projects/pull/302, to fix the licensing info.
