### ISSUE TITLE
Remove redundant license comments in built files

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#263]
I am not sure if this is still an issue, but it was originally reported here:

https://github.com/liferay/liferay-theme-tasks/issues/47

and mentioned in:

https://github.com/liferay/liferay-js-themes-toolkit/issues/48

I just added a PR that closes liferay/liferay-js-themes-toolkit#48:

https://github.com/liferay/liferay-js-themes-toolkit/pull/203

so I am creating this issue to reflect the open question about whether the originally reported issue is resolved.

I won't paste the original text in as it is rather long, but it basically boils down to many repeated instances of Lexicon copyright headers appearing in the built CSS.

**Comment by bryceosterhaus** [comment]
We updated this in DXP, we can likely use the same logic here https://github.com/liferay/liferay-portal/commit/c830340e5aba32ba16db06f22510177d38106fcd#diff-90bbbcd4776a36dac61f31129cb90fe3e3e8cb106b5432087753efbf0b16ef6a

**Comment by ambrinchaudhary** [comment]
I have just tested if this was still happening by generating a liferay-theme with the themes-toolkit, and checking the css generated and it does not contain multiple copyrights, but just one. 

These are the steps followed: 
1. On the` js-themes-toolkit` directory, run `yo liferay-theme`
2. For the theme generated, run `gulp build`
3. Check the css's generated in build/css. I've checked clay.css and main.css

Would you consider this "test" as valid? or should I check something else? Otherwise, I guess this issue could be closed as "fixed"

**Comment by izaera** [comment]
I would say that's enough :+1:

**Comment by ambrinchaudhary** [comment]
Thanks @izaera, closing issue then...
