### ISSUE TITLE
Standardize test directory structure

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#280]
At the moment we have:

1.  Projects that nest tests close to the corresponding source in `__tests__/` directories:
    -   `maintenance/projects/js-themes-toolkit-v8`
    -   `maintenance/projects/js-themes-toolkit-v9`
    -   `maintenance/projects/js-toolkit`
    -   `projects/js-themes-toolkit`
    -   `projects/js-toolkit`
2.  Projects that put tests inside `test/` at the top level, maintaining a parallel hierarchy to `src/`:
    -   `projects/amd-loader`
    -   `projects/npm-tools`
3.  Projects that are unique and beautiful snow flakes and do their own thing:
    -   `projects/eslint-config`: this one uses the structure provided by [ESLint's `generator-eslint` Yeoman plugin](https://www.npmjs.com/package/generator-eslint):
        -   `$PLUGIN_NAME/lib/rules` (source files); and:
        -   `$PLUGIN_NAME/tests/lib/rules` (test files).

Projects outside of this repo that may eventually get imported here currently follow these patterns:

-   [Clay](https://github.com/liferay/clay): nested `__tests__` folders (ie. **variant 1**)
-   [liferay-ckeditor](https://github.com/liferay/liferay-ckeditor): what tests?  (ie. **variant 0**)
-   [AlloyEditor](https://github.com/liferay/alloy-editor): top-level `test` folder (ie. **variant 2**)
-   [liferay-frontend-guidelines](https://github.com/liferay/liferay-frontend-guidelines): what tests?  (ie. **variant 0**).

Numerically speaking, `__tests__` predominates, and for good reason (it's a pretty common pattern out in the broader JavaScript ecosystem, and it makes it easy to jump back and forth between implementation and test files), so moving everything in that direction would be less work overall.

On the flip side, [our guidelines recommend the use of `test/`](https://github.com/liferay/liferay-frontend-guidelines/blob/master/general/file_names.md#why-testjs) because that's the way we do it in Liferay DXP (and the reason we do it that way there is to ensure that test files never make it into the built JAR files).

So we have a choice here and could go either way. I "like" `__tests__` better, but I also know that if we ever get asked to move the code into this repo into `liferay-portal` as part of some future hypothetical mega-monorepo-ization then it would be a difficult decision to unwind.

The other thing to note is that even with the `__tests__` pattern there is possible variation, because people can name their files `something.test.js` (we do this in js-toolkit, for example) or `something-test.js` (I don't think we do this anywhere) or just `something.js` (we do this in Clay; mostly it ends up being `index.tsx` but sometimes there are multiple files named after components). FWIW, the Jest documentation site starts its examples with `.test.js` suffixes, although most Facebook projects (including React, Relay etc) use `-test.js` suffixes. I don't really care about the choice here, although I do like the idea of explicit suffixes, but whatever we do we should make it consistent.

Finally: we should feel free to change the structure of the ESLint-generated tests because we are unlikely to ever use the generator (to create a new plug-in) again — any new rules we require will almost certainly go into one of our two existing plugins (ie. the `liferay` one which is used everywhere, and the `liferay-portal` one which contains DXP-specific stuff).

**Comment by jbalsas** [comment]
> [...] what tests? (ie. variant 0)

![likethewayyouthink](https://user-images.githubusercontent.com/905006/101658768-3c0f8c00-3a3d-11eb-9a4c-cb77ac95806e.gif)

**Comment by bryceosterhaus** [comment]
Personally I like the `__tests__` variant the most but it may just be that is what I have been used to.

**Comment by izaera** [comment]
A good thing about `__tests__` nested in the production code is that if you move the code it is much easier to move the tests along with it. In this sense, it's like more modular than the top level `test` folder.

Of course, I don't think that's enough to make us choose this pattern, but, I like it most, too, because of that (and because, for the very same reason, it is easier to browse the code and tests in UI interfaces, because you don't need to move too far :shrug: ).

**Comment by wincent** [comment]
As Oprah says, "You love `__tests__`! _You_ love `__tests__`! Everybody loves `__tests__`!".

![oprah](https://user-images.githubusercontent.com/7074/101749456-0b2b6780-3ace-11eb-90e3-a30aec2cc53d.gif)

**Comment by p2kmgcl** [comment]
I just found this issue, because I just created an `resources/test/page_editor/app/contexts/HelloPotato.test.js` and I think it is a bit difficult to find (the file I am testing is `resource/src/page_editor/app/contexts/HelloPotato.js`, maybe HelloPotato is not the real name of the file).

I want to vote for `__tests__` because:
1. It is easier to find if there is already a test file for a component/function/whatever.
2. I am lazy when creating new files, and having to replicate a whole file structure makes more lazy.
3. I prevents typos when creating new directories (`/tests/appp/contexts/...` this is actually not terrible but a bit annoying).
