### ISSUE TITLE
Include some animation/transition react library

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-projects#356]
I would like to create some transitions and animations in portal, but many times I need to use some JS to give some information to the CSS. Having some existing library for this task would be really nice. Can we discuss options for this?

Personally I do like CSS, and I like relying on transitions and keyframes, so I like to use [react-transition-group](https://github.com/reactjs/react-transition-group).

Any thoughts?

**Comment by kresimir-coko** [comment]
@p2kmgcl hey boi, what's the state of this issue?

**Comment by p2kmgcl** [comment]
Well we had other priorities and I never continued investigating this (honestly I forgot that this thread existed :sweat_smile:)

I have seen that react spring has gained a lot of popularity during these years, and I have seen really cool animations and tutorials with it (like [this intro from Josh Comeau](https://www.joshwcomeau.com/animation/a-friendly-introduction-to-spring-physics/)).

However I haven't used any of them on a real project, so I would like to hear if someone has actually used them.

**Comment by bryceosterhaus** [comment]
I would probably leave this decision up to each team, rather than provide a single solution. Particularly for animations and transitions, the need really varies from team to team and seems to be really particular for each use case. From my experience of working on various applications and working with various teams, it seems like a different type of animation library was needed for each use case.
