### ISSUE TITLE
Theme Generator for 7.3 doesn't seem to include a stylebook file

### ISSUE THREAD

**Issue by duracell80** [liferay/liferay-frontend-projects#380]
Stylebooks seem to be crashing in 7.3 with a custom theme when generated using the theme generator. There is a missing json file in /src/WEB_INF.

https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-classic/src/WEB-INF/frontend-token-definition.json

**Comment by jbalsas** [comment]
Hey @duracell80 thanks for reporting this!

We haven't decided on a developer experience path for Stylebooks yet, which is the reason why the don't get generated by default in `7.3`. We're trying to figure out the best way to expose this to developers. I acknowledge that simply creating an empty file would be a good start, but we realized that manually writing it would still be quite a bit of a hassle, so we're looking for some feature stability and feedback in order to inform our next steps.

Could you outline (if you have them) your expectations for how this could work from a developer persepective?

In any case, I think [Changing the default theme of a page set makes the common styles in the editor not working](https://issues.liferay.com/browse/LPS-119565) should've fixed this since themes do not necessarily need to provide a token definition.

Cc'ing here @dsanz, @david-truong so they can gather your insights and sharing it internally with Team Echo

**Comment by tdemnati-star** [comment]
Thanks Chema

**Comment by duracell80** [comment]
I totally understand. 7.3 is out and is being used by Enterprise level customers. Currently stylebooks are broken in a custom theme because of this missing file.

From a developer perspective, the file should be placed there by the theme generator. Period. Because I had no idea this file existed, or needed to.

From my perspective Stylebooks don't exist because they are not creatable in the global site, so I'm relying now on the theme to provide the only stylebook and I don't think I want my users being able to override our design system in the way that stylebooks allow. I have our design system set in the theme and that is the appropriate place for a qualified designer to implement a design system. Gene from accounting shouldn't be able to change my design system.

If stylebooks are not yet finished (clearly that's the case) ... please hide them and put the behind a feature flag.

So those are my initial thoughts on Stylebooks.

There's another issue with duplicating functionality again. We can define colors in the theme using color schemes. If the idea is to remove color schemes, please do not do that. The theme is still the best place to define a design system, the average site admin can't do this and won't have a need for stylebooks. Is good that the feature is there for designers who don't have access to the theme ... but as above until stylebooks are available in the GLOBAL site ... this feature doesn't exist to our use case which is multi-site commonality.

Liferay are ignoring the global site. It makes no sense. I can't import and export stylebooks on a site by site basis and I'm not even going to entertain the idea of multiple stylebooks until they are in the global site or multiple stylebooks can be defined in the theme. I don't want my site admins to have this feature. Period.

Global site yes ... Only a few people can get access to the global site and those people are qualified to create a stylebook ... Gene Charlene from HR cannot implement a design system.

**Comment by duracell80** [comment]
As for this ticket ... either fix the feature so that in a custom theme a token file isn't required (bad) or provide it in the theme generator (good).

**Comment by izaera** [comment]
Assuming that, since the above linked LPS has been fixed:

> In any case, I think [Changing the default theme of a page set makes the common styles in the editor not working](https://issues.liferay.com/browse/LPS-119565) should've fixed this since themes do not necessarily need to provide a token definition.

This is no longer a bug, at most a feature. So assigning that label for future grooming.

Feel free to comment if that's incorrect.
