### ISSUE TITLE
Update the no-metal-plugin eslint rule to reflect that 7.4 code should not make use of metal modules

### ISSUE THREAD

**Issue by dsanz** [liferay/liferay-frontend-projects#386]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [ ] :gift: Feature request
-   [x] :woman_shrugging: Other

### Description
Some time ago we started to [deprecate metal modules](https://issues.liferay.com/browse/LPS-96715). More recently, we started to [remove metal-dom usages](https://issues.liferay.com/browse/LPS-122383), and now we're [removing all usages of metal](https://issues.liferay.com/browse/LPS-124481) in DXP. This should lead to a deprecation of all metal modules during 7.4 release cycle.

In practise, this means that any developer who uses metal modules in their code should be warned of this deprecation process when building their modules.

**Desired behavior:**
The `no-metal-plugins` preset includes information about all metal modules, in a similar way as it does currently for a few of them. Documentation about the preset is updated.

**Current behavior:**
The `no-metal-plugins` preset includes information about some metal modules as part of the [LPS-96715](https://issues.liferay.com/browse/LPS-96715) deprecation effort

**Repro instructions (if applicable):**

**Other information (environment, versions etc):**
This updated preset shall be used for modules targeting DXP 7.4 as the most recent tasks dealing with usage removals will take effect in that release. It can be used in current master too.
For older releases (7.3 and 7.2), current preset has to be kept.

This task might need to wait till all usage removal tasks are done so that it can provide the proper explanation messages.

**Comment by wincent** [comment]
For the lazy, [here is the list of packages](https://github.com/liferay/liferay-frontend-projects/blob/6252b50e2082f30c6f438cf59a1b2b17d1b1e0b3/projects/eslint-config/plugins/portal/lib/rules/no-metal-plugins.js#L6-L17) we currently lint against in the `no-metal-plugins` rule.

The change should be pretty easy then:

- Add any additional plugins we want to blacklist to the rule.
- On older branches, where the updated rule will eventually arrive via backporting (of `liferay-npm-scripts` and therefore `@eslint/config-liferay`), we just need to opt out of the rule (we're [already doing this in `7.1.x`](https://github.com/liferay/liferay-portal-ee/blob/737e5eb78dff5cd2a4c6e30ce8ea7009d7def22d/modules/.eslintrc.js#L39) and would just need to do it on any branch where we aren't backporting our removal of usages of the Metal package. That is, we should control per-branch behavior via config in the `.eslintrc.js` files, as opposed to trying to fork the behavior at runtime via a code check.

**Comment by dsanz** [comment]
> That is, we should control per-branch behavior via config in the .eslintrc.js files, as opposed to trying to fork the behavior at runtime via a code check.

I see Greg, that sounds reasonable. If I understood, rather than having logic within the rule itself, the config per branch will change. In this case, it looks like we'll need 2 separate files for the rule in question: the one we have now and a new one for the additional modules. Then, the `.eslintrc.js` in 7.4 will add both, whereas the older branches will include just the existing rule. I'm not knowledgeable enough about eslint, what I wrote is just how things make sense in my mind.

Best

**Comment by wincent** [comment]
I think it's a bit simpler than that.

- [Current 7.1.x config](https://github.com/liferay/liferay-portal-ee/blob/737e5eb78dff5cd2a4c6e30ce8ea7009d7def22d/modules/.eslintrc.js#L39) has `'liferay-portal/no-metal-plugins': 'off'` in it; ie. we let people use any metal-plugin from [the list](https://github.com/liferay/liferay-frontend-projects/blob/6252b50e2082f30c6f438cf59a1b2b17d1b1e0b3/projects/eslint-config/plugins/portal/lib/rules/no-metal-plugins.js#L6-L17), which is currently:
  - `'metal-ajax'`
  - `'metal-aop'`
  - `'metal-clipboard'`
  - `'metal-debounce'`
  - `'metal-keyboard-focus'`
  - `'metal-promise'`
  - `'metal-storage'`
  - `'metal-structs'`
  - `'metal-uri'`
  - `'metal-useragent'`
- We add `'liferay-portal/no-metal-plugins': 'off'` to our [7.2.x config](https://github.com/liferay/liferay-portal-ee/blob/7.2.x/modules/.eslintrc.js) and [7.2.x config](https://github.com/liferay/liferay-portal-ee/blob/7.3.x/modules/.eslintrc.js).
- We add `metal-dom` and all the other removed packages to the list.

The net effect will be that you can use _none_ of the packages in `master`, and _any_ of the packages in older branches. You will note that this constitutes a relaxation of the rules for 7.2.x and 7.3.x, but it's a harmless one: there's no need to worry about new usages creeping in there because in theory new code is only being added to those branches via backports (ie. from `master`), and in `master`, we'll be making sure that new code using Metal plug-ins isn't getting in. Does that make sense? Basically optimizing for simplicity and stopping mistakes at the place where we would be most likely to commit them (`master`).

**Comment by wincent** [comment]
We previously had [a ticket for linting against `metal-dom`](https://github.com/liferay/liferay-frontend-projects/issues/216), but this one is more descriptive and generic, so I'm going to close that one and consider it to be folded into this one.

**Comment by brunofernandezg** [comment]
Jira ticket was manually created for this issue. Probably it won't be automatically updated so, please, let's do it manually. Thanks!
https://issues.liferay.com/browse/IFI-2325

**Comment by jbalsas** [comment]
Hey @kresimir-coko, assigned this one to you as well to see if we can wrap up the metal epic in its current state. 

See https://github.com/liferay/liferay-frontend-projects/issues/386#issuecomment-766996855 for how to execute this. Ideally we should add as deprecated in our `master` config every module not currently used in `liferay-portal@master`.

**Comment by wincent** [comment]
Fun fact: seeing this pop up in my inbox led me to look at the lint rule and I noticed [the human-readable error text is wrong on this line](https://github.com/liferay/liferay-frontend-projects/blob/6252b50e2082f30c6f438cf59a1b2b17d1b1e0b3/projects/eslint-config/plugins/portal/lib/rules/no-metal-plugins.js#L56), so we should fix that at the same time as well.
