### ISSUE TITLE
VSCode prettier integration for our rules?

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-frontend-projects#401]
Are there any recommended tooling or options to configure so that VSCode's prettier extension will work on save with our custom rules?

**Comment by izaera** [comment]
I used to work with VSCode and I think I got it working with our lints, but since I've switched to `vim` I cannot tell what I used :-(.

I usually installed the most downloaded plugins for each integration (so I used the most downloaded ESLint plugin for that, probably :sweat_smile: ). That's all I remember. Sorry.

**Comment by wincent** [comment]
@bryceosterhaus: have you checked out the stuff on VSCode in [the `npm-scripts` README](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/npm-tools/packages/npm-scripts/README.md#visual-studio-code)?

I don't use VSCode myself, but I know there are multiple people over here who are using [the wrapper](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/npm-tools/packages/npm-scripts/contrib/prettier/prettier.js) to get Liferay-style formatting in Liferay repos (and normal Prettier formatting in non-Liferay repos).

One "gotcha" to note is that VSCode caches extension stuff very aggressively, so in order to see it working you probably have to quit and re-open VSCode after configuring it for the first time.

**Comment by bryceosterhaus** [comment]
@wincent thanks for pointing that out. I'm pretty sure I read that exact readme looking for this info but I'm obviously blind. I'll give that a try.
