### ISSUE TITLE
Loading Environment Variables in React Portlet

### ISSUE THREAD

**Issue by sgreco-dev** [liferay/liferay-frontend-projects#404]
## What is your question?

I am trying to determine the best way to load environment variables during local development.  I have tried creating a .env file, which does not work out of the box.  I also tried installing 'dotenv' which gives me the following error.

```
Error: Can't resolve 'fs in 'C:\Users\xxxxxx\xxxxx\xxx\xxxxxxx\node_modules\dotenv\lib''
```

These variables are only needed for local development.  I am using the standard project starter by running 

```
yo liferay-js
```
generator-liferay-js@2.22.1

**Comment by wincent** [comment]
Unless I am misreading this, this isn't really specific to `generator-liferay-js` and is more about setting environment variables on Windows in general, right?

I haven't used `dotenv`, and much less on Windows, but there are [some Windows-related issues on their tracker](https://github.com/motdotla/dotenv/issues?q=is%3Aissue+windows) (7 open ones at the time I write this plus you can see there have been 15 issues closed in the past); not sure how smooth the user experience is on Windows with that project.

I'm not sure what shell environment you're working in, but is it possible that you could skip `dotenv` and just set the environment variables via some script that you source?

**Comment by sgreco-dev** [comment]
We were looking for some way to do this based off of .env files.  This would allow us to store values in a developers local environment to configure the project.  This such as API URL's, Local API Keys etc.  The main goal here is to allow our developers to configure their local environment without having to add certain things into the repo.  This is how we have handled it on standard projects, but it does not seem to be supported here.

For example.  We are using Liferay's Headless API, I cannot access that API from outside of Liferay unless we authenticate from the local environment, so the developer could just store their test account credentials locally for API access.

[React Env Variables](https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-envl)

**Comment by izaera** [comment]
Reading the document at the link you provided it seems that you are trying to use a feature of `react-scripts`, but you said you are using `generator-liferay-js` which uses a totally different build stack... Is that correct? :thinking:

Do you think you would you be able to use a simpler, different approach, or is there some reason that makes it impossible (I'm thinking about third party libs that assume that you use `react-scripts` or things like that...)?

I'm trying to find a way to do this in "developer's land" because the `generator` tries to be as agnostic as possible regarding the build process. Otherwise we would have to mimic all framework development tools that exist, which is impossible.

I'm not saying that it's impossible that we end up adding some kind of env var support as a feature, but as it is done right now, there's no code to handle that, nor to prevent you from doing anything you want with env vars in your build (unless there are unknown bugs that prevent it).

/CC: @david-truong

**Comment by izaera** [comment]
Also:

> the best way to load environment variables during local development

From where? Build scripts? Application code? If from application code, where will you be executing it?

Can you elaborate the question a bit more? Depending on where you want to access those variables there may be different ways to do it.

For example, if you just need credentials to login to a remote API from an application that is executing on Node.js you can simply use `process.env` and load the file yourself...

**Comment by sgreco-dev** [comment]
> Also:
> 
> > the best way to load environment variables during local development
> 
> From where? Build scripts? Application code? If from application code, where will you be executing it?
> 
> Can you elaborate the question a bit more? Depending on where you want to access those variables there may be different ways to do it.
> 
> For example, if you just need credentials to login to a remote API from an application that is executing on Node.js you can simply use `process.env` and load the file yourself...

Sure I can try to elaborate a little more on what we are trying to do.  There a couple different situations that I am attempting to address.

The first is that I am trying to allow our other developers to maintain a .env file inside their local project.  This file will contain things like credentials for local API access, API URL's etc.  These are unique to the user and we would like to not have to hard code them into the application.  

The second situation, is that we might want to read in certain variables at build time when a production build is being done.  This might contain different environment level properties that would be different for someone working on their local version of Liferay.

So essentially we would want to access these variables when using the local webpack dev server, as well as at build time.  That is why we were attempting to use the standard dotenv package as detailed in the create-react-app documentation.  This way we could split our properties/variables for local development and build environments (DEV, QA and PROD).

The workaround I have seen in other issues seems to be setting webpack to target="node", but I am not sure where to edit the webpack config, it seems to get generated automatically.

**Comment by izaera** [comment]
> using the local webpack dev server,

If by that you refer to the one the generator configures for the `start` target then you can configure certain things, but be warned that the `start` feature was created as an experimental feature and has not been developed any longer because it is impossible to make it generic enough without arriving to a very unstable and fragile setup. Also, the available configuration is very narrow.

It would probably be faster and better if you create your own webpack integration for your project so that you can tweak it as you like.

If you want to have a look at what the `start` script of the JS Toolkit does, [this](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/packages/liferay-npm-build-support/src/scripts/start.js) is the right place. It simply creates a webpack configuration from some values inside the `.npmbuildrc` file (`cfg.getWebpackPort()`, `cfg.getWebpackProxy()`, etc in that code) and launches webpack.

A good way to do your custom integration could be running `start` once and then base your solution on top of the generated webpack configuration file. That way you don't have to start from scratch :-).

**Comment by izaera** [comment]
Closing this as answered. Feel free to reopen if necessary.
