### ISSUE TITLE
Css from dependencies not being included into bundle

### ISSUE THREAD

**Issue by jtumano** [liferay/liferay-frontend-projects#410]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Description
I'd like to add some extra css into theme, for example add into package.json `material-design-icons-iconfont` and include it in **_imports.scss** like `@import "~material-design-icons-iconfont/dist/material-design-icons.css";`

**Desired behavior:**
css is existing in portal after theme deploy

**Current behavior:**
css is not being bundled and getting error message in browser console: 
`Refused to apply style from 'http://localhost:8080/o/my-liferay-theme/css/~material-design-icons-iconfont/dist/material-design-icons.css?t=1613737834034' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

**Repro instructions (if applicable):**

**Other information (environment, versions etc):**
also tried to use relative, absolute etc paths and it still doesn't work

**Comment by wincent** [comment]
Do you have a sample theme that you could link to that exhibits this problem?

**Comment by jtumano** [comment]
created sample theme: https://github.com/jtumano/liferay-dependency-bug-theme

Check this line: https://github.com/jtumano/liferay-dependency-bug-theme/blob/8754c0d75ceee90c4e18234371554bd73aab839c/src/css/_custom.scss#L8

also the final war doesn't contain any material-icons-iconfont data inside

**Comment by bryceosterhaus** [comment]
Hey @jtumano, sorry for the delay in getting back to you on this issue.

Try updating your import to look like this.

```diff
- @import "~material-design-icons-iconfont/dist/material-design-icons.css"; 
+ @import "material-design-icons-iconfont/dist/material-design-icons"; 
```

When we build your scss files in your theme, we include `node_modules` as an [includePath](https://sass-lang.com/documentation/js-api#includepaths), so when the compiler sees `material-design-icons-iconfont`, it checks for that directory in node_modules. Secondly, remove the `.css` extension so that it doesn't try to make a network request for that file. Sass sees the extension and instead of importing the file at build time, it tries to request it at run time.

Let me know if you have any questions or issues. I'll respond more promptly than before.

**Comment by bryceosterhaus** [comment]
Going to close as resolved, but if it doesn't work for you. Feel free to comment and I can re-open
