### ISSUE TITLE
Publishing AMD Modules in WAR style apps (Spring MVC)

### ISSUE THREAD

**Issue by japfohl** [liferay/liferay-frontend-projects#413]
Is it possible to use the liferay-npm-bundler as a part of WAR style applications?  I did a bunch of experimentation on my part and was able to successfully bundle and include a bunch of files and npm dependencies in a Spring MVC portlet app but every time if was being processed after getting picked up by the FlatNPMBundleProcessor._processNodePackages it threw a NPE.

To get it to be picked up I bundled the files in /WEB-INF/classes/META-INF/resources using the Maven War Plugin (maven is a strict requirement where I work) but I'm stuck on this NPE.  Any help would be greatly appreciated.  

The version in question is DXP 7.0.10-sp15 backed by Oracle 12c.  Everything is running in Docker containers.

**Comment by izaera** [comment]
No, as you have found out, it won't work :-(. This is because all the machinery to inspect OSGi bundles assume the structure of the bundle is a true OSGi module and WARs aren't. 

Even though WARs are lightly wrapped and adapted by Liferay to look like OSGi modules, they lack many of their features and its support is provided for compatibility reasons.
