### ISSUE TITLE
Code Formatting Standards

### ISSUE THREAD

**Issue by miltonmc** [liferay/liferay-frontend-projects#427]
## What is your question?
Why do we use 80 chars per line and tab for indentation to format our Javascript source?

## Some context 
I'm new here at Liferay (around 45 days) and I'm trying to figure out what is behind the decision/motivation of not following JS community standards on our code formatting, that is 120 characters per line and 2 white spaces to indent.

IMHO these choices we made brings negative impact on code readability, but maybe there is a strong motivation that I was not able do understand so far.

**Comment by wincent** [comment]
> what is behind the decision/motivation of not following JS community standards on our code formatting, that is 120 characters per line and 2 white spaces to indent.

None of the things you mention are community standards. The closest thing to "a community standard" would be [near-universal use](https://2020.stateofjs.com/en-US/other-tools/utilities) of [Prettier](https://prettier.io/), which uses [a default print width of 80 columns](https://prettier.io/docs/en/options.html#print-width). Funnily enough, they even say (emphasis added):

> For **readability we recommend against using more than 80 characters**:
>
> In code styleguides, maximum line length rules are often set to 100 or 120. However, when humans write code, they don’t strive to reach the maximum number of columns on every line. Developers often use whitespace to break up long lines for readability. In practice, the average line length often ends up well below the maximum.

As for use of tabs instead of spaces, you'd have to convince [the Chief Software Architect](https://web.liferay.com/about-us/leadership/bchan) that 2-space indents are better than tabs, but there are probably more productive uses for your time. It is a long-running religious war after all ([example](https://softwareengineering.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e)). Any decent code editor can be configured to display tabs with whatever width you like, and even allow you to have per-project overrides. Even if you don't want to do that, Prettier will "fix" anything that you write in a non-conforming style. My own personal experience joining Liferay after working professionally in environments that use 2-space indents for over 10 years (and before that, 4-space indents): configured my tools and moved on. After brief initial discomfort, familiarity makes the new pattern just as readable as anything I'd ever had to live with before; the important part is being consistent, and thankfully tools like Prettier and good code editors make it easy to do so.

I'm going to close this because it is not actionable, but you are welcome to carry on the conversation if you think there is more ground to be covered.

**Comment by miltonmc** [comment]
@wincent, first of all I would like to thank you for your answer!

After all, my real concern is related to avoid line breaks and we could do that allowing a print width of 120, also using a 2-space indentation (it really doesn't matter if we are doing that using tab or whitespace) and even more combining both.

I believe our current standar could be especially annoying writing JSX.

A code like [this](https://github.com/liferay/liferay-portal/blob/95a3c72b8409afb58284282eef3a3f9417561cd9/modules/apps/data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/components/sidebar/MultiPanelSidebar.es.js#L291-L300) (please consider that it is already nested into other tags)
```javascript
<div
	className={classNames({
		'd-none':
			panel.sidebarPanelId !==
			currentPanelId,
	})}
	key={panel.sidebarPanelId}
>
	<panel.Component />
</div>
```
would became
```javascript
<div
	className={classNames({
		'd-none': panel.sidebarPanelId !== currentPanelId,
	})}
	key={panel.sidebarPanelId}
>
	<panel.Component />
</div>
```
or
```javascript
<div
  className={classNames({'d-none': panel.sidebarPanelId !== currentPanelId})}
  key={panel.sidebarPanelId}
>
  <panel.Component />
</div>
```

**Comment by wincent** [comment]
> especially annoying writing JSX.

Yes, this is true. We have plenty of examples of deeply nested JSX that is very hard to read (not so much in the editor, but on GitHub, were space is constrained _and_ tabs get rendered as 8 wide, making it worse).

Having said that, it is unlikely we'd be able to implement any change here, because the Java style is very entrenched at Liferay after 15+ years, and the JS style largely "rhymes" with the Java style in the name of _global consistency_, which is highly valued by Brian. This means that, even though you can make a good case that files containing complex/nested JSX would look much better with a wider column limit and/or a narrower indent, you would have a very high barrier to overcome if you want to convince people that it's ok for stuff to look one way in JS, and another in JSP and `.java` files...
