### ISSUE TITLE
Add react-flow library to the portal

### ISSUE THREAD

**Issue by naraandrade** [liferay/liferay-frontend-projects#447]
## What is the new or updated dependency?
Hi, I would like to request the addition of the React Flow library to the portal.
Repo: https://github.com/wbkd/react-flow
Docs: https://reactflow.dev/docs/

## Why is this dependency useful to you and others?
I'm from Workflow team and, currently, we are developing an updated version of Kaleo designer, the Workflow Powered Apps (integrating App Builder and Workflow). Until now, we had developed an MVP, allowing only the construction of linear flows of steps, but to evolve the project, we will need to allow the construction of complex flows, with conditions and parallel paths, for example. And for that, this library would enable us to develop these features much faster than if we created a new builder from scratch.

## What are the alternatives?
We have already evaluated how complex it would be to create our own builder (taking advantage of some functions of the aui diagram builder), but this would have a major impact on our delivery times.

We have made a POC (https://github.com/liferay-workflow/liferay-portal/pull/269) of the usage of the library within our code and we were able to validate that we would be able to use it without problems for the purposes we want, just making some adjustments in our current structure.

**Comment by wincent** [comment]
@naraandrade: That looks quite reasonable to me. We (Frontend Infra) can certainly comment on libraries that you want to add if you want our opinion on them, but we don't have a formal approval policy in place that you have to go through before adding a dependency. ([The opposite is true for `devDependencies`](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/dxp/dev_dependencies.md), where you have to fill out a Form 990A, submit 0.21 BTC in processing fees, and contribute a minimum of 3 goats, 6 chickens, and 1 sheep to the Frontend Infrastructure Farm — 2 cows if you want expedited service.)

The kinds of things we look at when evaluating libraries are:

- Popularity (GitHub stars) and usage statistics (npm downloads).
- Development activity (what does the commit and release history look like?).
- Issue/pull request activity (how many open? how responsive are the maintainers?).
- History of breaking changes (how much work will it be staying in sync with the latest version of the library?).
- History of security issues (how likely are we to have to drop everything and do a forced update because of a security issue?).
- License compatibility (is the license on our list of approved OSS licenses?).
- What is the feature set of the project and how good is the documentation?
- How good is the code quality (just based on a quick inspection of the codebase)?
- How performant/small is the library relative to the value it delivers (ie. wanting to avoid the "death by a thousand cuts" phenomenon caused by bloating the product with many libraries that each contribute a small amount in isolation, but impact the overall product experience quite noticeably when used in combination).
- Dependency footprint (what will bringing this library drag along with it, and how do the questions above apply to the transitive dependencies?).

And probably some other things that I have forgotten... in short, because there are so many ways in which a library can _hurt_ us, we tend to be very conservative about what we add, because it is often much harder to undo the decision to add a library than it was to stick it in the first place, and the cost of maintaining a library in good working order inside DXP is usually much higher than you might think.

Having said all that, the choice is up to your team! If you do decide to go with a library like this, you can use it locally in your projects, and if you are worried about having multiple copies of the library floating around at once, you could add it in a centralized location and configure the bundler to load the single shared copy from all the places that you need to use it — but this would be a location you control and not an "official/global" shared location that Infrastructure would maintain and support.

Going to close this for now, but let us know if you have any further questions or thoughts.

**Comment by naraandrade** [comment]
@wincent Loved your humorous answer 😆 Thank you very much for your considerations

**Comment by jbalsas** [comment]
Dropping DiagramBuilder and friends... music to my ears 😍 

![shutupandtakemymoney](https://user-images.githubusercontent.com/905006/111166928-86eaf380-8598-11eb-9b5c-3e9a95c5ef3a.gif)
