### ISSUE TITLE
CSS guidelines: review, fix and extend

### ISSUE THREAD

**Issue by edalgrin** [liferay/liferay-frontend-projects#512]
## What is your proposal?

To review the current CSS guidelines, fix some typos and eventually add missing information

## Why would adopting this proposal be beneficial?

To have a clear indication of the used best practices and convention

## What are the alternatives to this proposal?

Create a tool that help us during the formatting and creation of these sections

**Comment by wincent** [comment]
> Create a tool that help us during the formatting and creation of these sections

Sounds like overkill 😂 but I can understand why you would want to do this and I like the way you think. 😁 

In any case [Prettier is supposed to format code inside Markdown](https://prettier.io/blog/2017/11/07/1.8.0.html). If it is failing to do so in a case like the following, then that sounds like a bug we should [report upstream](https://github.com/prettier/prettier/issues/new/choose) instead of building a tool when there are other fires that should be put out first:


```
-   src
    -   text-editor
        -   text_editor.scss
    -   blog
        -   \_blog.scss
    -   main.scss
        ```scss
        @import blog/_blog.scss;
        @import text-editor/text_editor.scss;
        ```
```

**Comment by edalgrin** [comment]
I can't right now so I prefer to close it and reopen it when it's necessary
