### ISSUE TITLE
Update the theme-unstyled dependency version

### ISSUE THREAD

**Issue by edalgrin** [liferay/liferay-frontend-projects#536]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [x] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :eight: v8.x
-   [ ] :nine: v9.x
-   [x] :keycap_ten: v10.x or higher

### Description

During the fixing of a bug I noticed that for 7.3 themes, we are loading the wrong version of `Clay` (2.x) as a dependency of the wrong version of `theme-unstyled` (5.0.0), to fix it we should use 5.0.3 instead.

Bug: https://issues.liferay.com/browse/LPS-130181
Slack discussion: https://liferay.slack.com/archives/C3JBR21HA/p1620831949446300

**Comment by izaera** [comment]
This is already [fixed in master](https://github.com/liferay/liferay-frontend-projects/blob/f97ae3e0a79b7f9e583bf48294a37539d6e8cdfc/projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/devDependencies.js#L66-L68), we just need to release a new version of the Themes Toolkit to npm, but we are waiting for QA to finish before doing it.
