### ISSUE TITLE
How to Extend Bundler Preset?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-frontend-projects#538]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [X] :thinking: Question
-   [ ] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [X] :two: v2.x
-   [ ] :three: v3.x

### Description

What is the best way to extend/override a bundler preset?

In my particular case I am using create-react-app, followed by the liferay-js:adapt style adapter...

I would like to tweak the JS files in the 'static' folder so that they all have define('xxxx',**['module'])** changed to something like define ('xxxx',[**'module','common_runtime'**]) but i am not exactly sure how i could do that and still leverage the bundler's react preset

**Comment by izaera** [comment]
Presets cannot be extended but overriden. 

That means that you may put only one `preset` in your `.npmbundlerrc` file and that's the only preset you are going to have in your build. Not even a preset is able to extend other preset.

The rationale behind this is that if we let multiple presets to be used, a lot of issues could appear like, for example:

- Circular dependencies
- Multiple inheritance
- The lack of a way to remove things from base presets (you can only add/overwrite)
- The lack of a proper merging strategy that can suit all scenarios

So, in your case, I would say that the best way would be using the `create-react-app` preset and add anything else you need to your `.npmbundlerrc` file. Alternatively, if you want to reuse that customization you make in more than one project you can copy [our preset](https://github.com/liferay/liferay-frontend-projects/tree/master/maintenance/projects/js-toolkit/packages/liferay-npm-bundler-preset-create-react-app), customize it, and publish a package of your own with it.

The only downside to that is that, if we publish a new version of our presets, you need to update your preset by hand. But, in any case, you would have to update your dependencies at the very least, so it's not so bad. Also, in the case of adaptations, it is unlikely that you could benefit from a new version of that preset because they are usually published to support a newer version of react (and even then, they don't change so much).

**Comment by izaera** [comment]
Regarding the other part of the question:

> I would like to tweak the JS files in the 'static' folder so that they all have define('xxxx',['module']) changed to something like define ('xxxx',['module','common_runtime']) but i am not exactly sure how i could do that and still leverage the bundler's react preset

What files? The output of webpack (bundle .js files)? You source files? :thinking: It depends a lot on when you want that transformation to happen...

When would you say that transformation should took place ? Before the react-scrips are invoked? Before the bundler adapts the output of the npm-scripts? After that? ...

**Comment by mfreeman-xtivia** [comment]
Yes the files output by webpack.

And the desire would be to do this before the bundler creates the JAR whenever/wherever is the best time to do that

**Comment by izaera** [comment]
In that case I would probably copy-paste the preset and add a new loader to [these ones](https://github.com/liferay/liferay-frontend-projects/blob/109e64d1a0394b3262faa61adb991ad224bc8373/maintenance/projects/js-toolkit/packages/liferay-npm-bundler-preset-create-react-app/config.json#L37) to do that processing.

You could even use an existing one like the [replace-regexp one](https://github.com/liferay/liferay-frontend-projects/blob/109e64d1a0394b3262faa61adb991ad224bc8373/maintenance/projects/js-toolkit/packages/liferay-npm-bundler-preset-create-react-app/config.json#L47) if you want to/can do it using regular expressions (see the source code of that loader [here](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/packages/liferay-npm-build-support/src/loader/replace-regexp.ts)).

If you need to write your custom loader there's the [loader API](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/api/loaders.ts) and [some documentation](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-write-your-own-loader.md).

Hope that helps.

**Comment by izaera** [comment]
I'm closing this as replied. Feel free to add comments as needed.
