### ISSUE TITLE
DXP is currently using an outdated version of @testing-library/react

### ISSUE THREAD

**Issue by diegonvs** [liferay/liferay-frontend-projects#554]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [X] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Description

While implementing tests I notice some inconsistencies between our version of react/testing-library and the current(21th May version). Methods like [waitFor](https://testing-library.com/docs/dom-testing-library/api-async#waitfor) aren’t available and for some cases I need to use waitForElement which is currently deprecated.

When running `yarn why @testing-library/react`:

```log
=> Found "@testing-library/react@8.0.9"
info Reasons this module exists
   - "_project_#@liferay#npm-scripts" depends on it
   - Hoisted from "_project_#@liferay#npm-scripts#@testing-library#react"
```

The version detected is 8.0.9 but the current version of this library is [11.2.7](https://www.npmjs.com/package/@testing-library/react). Do We have plans for updating it?

Taking a look on codemods for a possible migration I found few and reliable results:

* https://github.com/atsikov/eslint-jest-testing-library-codemod
* https://gist.github.com/dslemay/fde3b76ab59eaa2b6b4a15896d699f57

### Compiling major version changelog of @testing-library/react, I see:

**[8.0.9](https://github.com/testing-library/react-testing-library/releases?after=v9.3.0) dates Aug 2019, the next version is the 9.0.0 where the breaking changes are:**

deps: If you were using debugDOM before, use prettyDOM instead. Note that debugDOM is different from debug which you get back from render. That is unchanged.

cleanup: If your tests were not isolated before (and you referenced the same component between tests) then this change will break your tests. You should keep your tests isolated, but if you’re unable/unwilling to do that right away, then you can either run your tests with the environment variable RTL_SKIP_AUTO_CLEANUP set to true or import @testing-library/react/pure instead of @testing-library/react.

cleanup-after-each: If any of your code has import '@testing-library/react/cleanup-after-each' then you need to remove that. It’s happening automatically now.

**From 9.x to 10.x**

Drop Node 8

Node 10 or greater is required. Node 8 is out of LTS (#576) (fccc2cf), closes #575

remove deprecated cleanup-after-each.js

This file which did nothing but log a warning to the console (#598) (7942f68)

- import '@testing-library/react/cleanup-after-each'
+ // nothing! Just remove it

As a general reminder, you should NOT need to use cleanup at all as this is done automatically for you (unless you’re using @testing-library/react/pure in which case you know what you’re doing... keep using cleanup).

**From 10.x to 11.x**

cleanup is now synchronous and wraps the unmounting process in act.

### Risks

About the risks of migrating, what my limited vision see:

**From 8 to 9**, I think We can break some tests if the component is being reusable on the test. Like rendering just one component and the following test cases depends in this instance. Regarding the cleanup after-each We can use a codemod for it.

**From 9 to 10**, If We don’t use node 10 or greater it will not work.

**From 10 to 11**, I don’t see it breaking everywhere but We can make tests

**Comment by miltonmc** [comment]
@bryceosterhaus I heard that @jbalsas will be OOO for sometime, so could you help me with this issue?

**Comment by bryceosterhaus** [comment]
Hey @miltonmc yeah I can try to help you out. Which parts of the new version of testing-library are you dependent on? Is your current test case possible to achieve with older APIs from testing-library?

**Comment by miltonmc** [comment]
Hi @bryceosterhaus,

I've faced an already closed issues using the `userEvent.type()` and had to do an [ugly hack](https://github.com/liferay/liferay-portal/blob/cbb73af51883b8ddb6925f2c6e6a1af4013dcfd2/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/test/js/Numeric/Numeric.es.js#L137-L144).

Beside that, there are a few techniques described by Kent C Dodds in his [article](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library)  that I would like to try. Like remove the `cleanup` in the `afterEach` test hook and use `screen` instead of `render`.

So, would be good to have the at least the `@testing-library/user-event` up to date. 

Thanks for the help!

**Comment by bryceosterhaus** [comment]
@miltonmc, unfortunately I think I would probably just stick with the hack for now. Updating this dependency and the tests that rely on it is pretty far down our to-do list and not sure when we will get a chance to spend time updating it. I will keep you posted when we do find some time to update though.

**Comment by miltonmc** [comment]
@bryceosterhaus I've just got another situation due to usage of the outdated dependencies. 

I was intent to write a new test case for a pasting value situation and faced the error: `TypeError: _userEvent.default.paste is not a function` and just now I realized how far from the latests releases we are, for some dependencies. We are using [@testing-library/user-event@4.2.4](https://github.com/liferay/liferay-frontend-projects/blob/1a95f02204294dc378445a1ef9cfcdc39df9fca9/projects/npm-tools/packages/npm-scripts/package.json#L24) while today the latest is [@testing-library/user-event@13.1.9](https://github.com/testing-library/user-event/tree/v13.1.9).

Besside the fixes we are missing, there are a bunch of new and super useful features unavailable to be used to test the portal's code. 

>The more your tests resemble the way your software is used, the more confidence they can give you.
Kent C Dodds


Some of the behaviours we are not easily able to do in resembling the way our users do:
- hover
- paste
- upload files
- tab navigation
- hover
- unhover
- paste data

If we really want  to leverage our code coverage and at same time not penalising  CI execution time, I think we should start prioritise activities like this.

I would love to contribute to have this activity done, just let me know how can I help on that. I could start trying to update `@testing-library/user-event` on a branch, force a branch from portal to use that and see how bad we are. Depending on the results I can try to fix the issues. What do you say so?

**Comment by bryceosterhaus** [comment]
@miltonmc I really appreciate your willingness to help! One way that you could help get this through is by checking DXP for the extent of updates we would need to do. To check this, you would have to update DXP to use that version of testing library and then run all of our unit tests in DXP. You can run every test with this script from `liferay-portal/modules`.

```bash
git grep -l '"test": ".*liferay-npm-scripts test.*"' -- '*/package.json' package.json | \
xargs -n 1 dirname | \
xargs -n 1 -o bash -c 'cd ${!#} && yarn test $0 "${@:1:$#-1}"' "$@"
```

In order to get DXP to use the newest version of testing library and user event, I think you could use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) but I am not positive about that.


Once we get an idea of how many failures or errors there are, we will have an idea how hard the upgrade path will be.

Thanks again for being willing to help!

**Comment by victorg1991** [comment]
I'm taking over this. A new version has been release since last comment on this issue:

#### v12.0.0

The breaking changes are:

- drop node 10 support ❌. I think try to go for the v11 until we also drop the node 10 support 
- update @testing-library/dom to 8.0.0 which itself brings the following breaking changes:
    - Remove deprecated waitFormDOMChange ✅(we are not using that anywhere) 
    - Remove deprecated waitForElement ❌ (155~usages, used `git grep 'waitForElement\(' -- '*.js' | wc -l`)
    - The timeout in waitFor(callback, { interval, timeout } ) now uses the same clock as interval. Previously timeout was always using the real clock while interval was using the global clock which could've been mocked out. For the old behavior I'd recommend waitFor(callback, { interval, timeout: Number.POSITIVE_INFINITY }) and rely on your test runner to timeout considering real timers. 🌫 (doesn't seems like something we should worry about, but a deeper analysis may be needed)
    - <script />, <style /> and comment nodes are now ignored by default in prettyDOM .If you wish to return to the old behavior, use a custom filterNode function. In this case prettyDOM(element, { filterNode: () => true }) (same as before)

After checking that I think we may try to upgrade to v11.0.0 in the mean time while we drop support for node 10 and then try to upgrade to the v12, thoughts @bryceosterhaus ?

**Comment by bryceosterhaus** [comment]
> I think try to go for the v11 until we also drop the node 10 support

This makes sense to me, and we would have to makes these updates anyways for v12 so these changes will be helpful regardless.

**Comment by victorg1991** [comment]
Started checking this again, now we can jump directly to the v12 since node 10 support is already dropped :) It seems that a bunch of tests failed, once I have specific number I'll keep this updated

**Comment by bryceosterhaus** [comment]
Thanks for looking into this @victorg1991 !

**Comment by victorg1991** [comment]
This is already available in master!!

**Comment by victorg1991** [comment]
k
