### ISSUE TITLE
Setup eslint in a liferay-js-toolkit project?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-frontend-projects#585]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ X ] :thinking: Question
-   [ ] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

How does one go about adding eslint to a standard liferay-js-toolkit project (i.e., one **not** created through adapting a CLI)

I need to activiate eslint and then add a couple of specific eslint plugins but its not obvious to me where/how one does that

**Comment by izaera** [comment]
There's no standard way to do that since JS Toolkit is agnostic of any other tools you want to use in your project. It only does the build part related to Liferay deployment, but nothing prevents you from adding tests, linters, formatters, or even a build for a target other than Liferay...

So you should be OK following [eslint's standard documentation](https://eslint.org/docs/user-guide/getting-started)...

**Comment by izaera** [comment]
I'm closing this as answered, feel free to add more comments if you need further help :-)
