### ISSUE TITLE
Updating CodeMirror version

### ISSUE THREAD

**Issue by oliv-yu** [liferay/liferay-frontend-projects#609]
## What is the new or updated dependency?
CodeMirror v5.59.1 for liferay-portal master 

## Why is this dependency useful to you and others?
Our QA team on Search found there was a bug occurring when using CodeMirror, the Ctrl-C copy and Ctrl-V paste were not working on Chrome versions 91, 86, and 65 for Linux users. It seems like this was a known issue on CodeMirror v5.59.0 (https://github.com/codemirror/CodeMirror/issues/6548) that's fixed on the next version 5.59.1. Our QA team was able to check with a sandbox https://codesandbox.io/s/nervous-cookies-7pxui with the different versions and confirmed that it was working on 5.59.1, so we hope updating it will fix the problem.

We wanted to know, are we able to specify our own version of CodeMirror in this Search module? That would cause multiple versions of CodeMirror in portal. However, this change could be made across portal to fix the copy/paste issue, like in Fragments. Please let us know what you guys think!

## What are the alternatives?
Since this is not considered a major bug, we haven't considered many alternatives. 

@thektan

**Comment by nhpatt** [comment]
Hi Olivia!

Yeah, it's perfectly Ok to have several versions of the same dependency, not ideal but sometimes is unskippable.

I've checked the current uses of `CodeMirror` with `yarn why` and it seems it's being used only by Echo team (fragment-web and journal-web) and our team (headless-discovery-web)... 

*But* discovery-web is a package with a custom webpack configuration that lives outside the portal lifecycle so it can have a completely different version. It seems that package is the one "anchoring" to that version (via a graphiql transitive dependency) and we can't not update it freely because a node version limitation. So we can ignore that dependency... it'll be using 5.59.0 until we solve those issues. So there is no need to coordinate with our team :)

But, ideally, we could use the same version inside the portal, if you force a newer version in echo projects (bump those ^5.52.0 to 5.59 or more) I guess all (fragment, journal and yours) will end using the latest... just ping Echo team in slack/github and send them the PR to make sure everything on their side is working.

Closing the issue here (please reopen if you have any doubts) because it's an Echo & Search coordination now :D
