### ISSUE TITLE
Can generator-liferay-js generate two separate widgets inside the same project?

### ISSUE THREAD

**Issue by PasinduDineth** [liferay/liferay-frontend-projects#611]
I have used generator-liferay-js to generate a react based project. Is there anyway I can create two different widgets using the same project and deploy as two widgets? liferay developer studio can do modularization and generate two or more widgets using one code base.  Is there anyway to use generator-liferay-js to do such a thing?

Thanks

**Comment by izaera** [comment]
Hi @PasinduDineth. What you are asking for is not possible, because the portal doesn't alllow you to implement more than one JavaScript portlet per project/OSGi bundle/JAR file. This is because it uses some files that are unique inside each JAR file to register things in OSGi on behalf of the JS code (for example: it gets the portlet name from the `package.json` file).

On the contrary, if you create a project based on Java you have full access to Liferay/OSGi backend APIs and you can put as many portlets as you want in a single OSGi bundle.

Hope that answers your question. I'm closing the issue, but feel free to comment any further doubt you may have.
