### ISSUE TITLE
Investigate changelog generator not working properly in this repo

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-frontend-projects#732]
I've had a few instances where I try to generate the changelog and it behaves really strangely. For example, when trying to generate a changelog for eslint-plugin/v1.1.0, it only produced one chage.

My working theory is that it has something to do with either my specific git config, or possibly due to the repo merge of alloyui

**Comment by izaera** [comment]
Shall we close this after finding out it was an extension issue? Or do we want to try to make it work even for empty merge commits? :thinking: 

I doubt it will be an easy thing because otherwise Greg would have done it probably, as it took a lot of time to find out the problem.

Maybe we can add an error message in case the merge commit is empty. That would be a compromise solution.

**Comment by nhpatt** [comment]
compromise solution sounds good

**Comment by bryceosterhaus** [comment]
I think we can just blame the original creator of the ticket and continue as normal. If anything else pops up we can create a new issue.

@bryceosterhaus just needs to get his act together and stop using extensions 😂

**Comment by izaera** [comment]
> I think we can just blame the original creator of the ticket and continue as normal.

Yeah, let's do that...

![to the fire](https://media.giphy.com/media/2A4DpHThLo2z0GOhxC/giphy.gif)
