### ISSUE TITLE
System configuration category name, is not localized. also i see no way to tell it what section to be in.

### ISSUE THREAD

**Issue by scavezze** [liferay/liferay-frontend-projects#785]
I added the following to  features/localization/Language.properties 

category.test-js-portlet=Test Category name

and the configuration.json has the following

`{
	"$schema": "https://raw.githubusercontent.com/liferay/liferay-js-toolkit/master/resources/schemas/configuration.schema.json",
	"system": {
		"category": "test-js-portlet",
		"name": "test-js-portlet",
		"fields": {
			"fruit": {
				"type": "string",
				"name": "fruit",
				"description": "fruit-help",
				"default": "orange",
				"options": {
					"orange": "an-orange",
					"pear": "a-pear",
					"apple": "an-apple"
				}
			}
		}
	},
	"portletInstance": {
		"fields": {
			"drink": {
				"type": "string",
				"name": "drink",
				"description": "drink-help",
				"default": "water",
				"options": {
					"water": "water",
					"wine": "wine",
					"beer": "beer"
				}
			}
		}
	}
}`

But in the Liferay -> System -> Settings the system category name is category.test-js-portlet

I also don't see anything in the schema that would let me move it out of the Other section

**Comment by izaera** [comment]
This is the place in `liferay-npm-bundler` where the `configuration.json` file is converted to the `OSGI-INF/metatype/metatype.xml` file :point_right: https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/index.js#L174

Apparently it is taken [from the `name` field](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/index.js#L181) of the `configuration.json` file...

**Comment by izaera** [comment]
If I am not mistaken, you may need to deploy something to the portal (an OSGi bundle I mean) to configure how system settings categories are displayed and ordered.

There's nothing in the JavaScript project that may be done to configure that, since it is in a higher level than any project itself. I mean, AFAIK, system settings categories can be shared among several OSGi bundles, so it's not something that is modularized on a per project basis...

**Comment by izaera** [comment]
OK, checked this a bit more:

> But in the Liferay -> System -> Settings the system category name is category.test-js-portlet (not localized)

This may be a bug, or at least needs some more investigation to see how it can be localized.

> I also don't see anything in the schema that would let me move it out of the Other section

There are two fields in `configuration.json`: `name` and `category`. Those two fields are used to give a name to the configuration and place it under a category.

The `Other` section, by definition, is `Other` for anything not coming from Liferay itself (as per the System Settings functional requirements). So that is working as it was designed.

**Comment by izaera** [comment]
I've changed the type of issue to `bug` until it is clear if localization should be done in the JS project or server side.

**Comment by izaera** [comment]
I can confirm that values shown in the configuration UI are localized:

(the strings inside square brackets are the localization keys as defined inside the `features/configuration.json` file of a default project named `Test`)

![image](https://user-images.githubusercontent.com/3273630/162423767-12600114-e715-429b-b428-d58846f64c43.png)

Regarding the category name, it is outside of the scope of JavaScript portlets, because categories must be deployed as JAR projects, given that they can be reused between several portlets/OSGi bundles

In this case, [there exists a localized `Test` category](https://github.com/liferay/liferay-portal/blob/1dbc1eebe8b4abad84c455bf768b62f1726f8a39/modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties#L2773) OOB in Liferay Portal, thus it is shown as a proper string, instead of as `category.test` but, in general, the user must deploy a proper configuration category if he wants to use it.
