### ISSUE TITLE
yarn format don't reach the npmscripts.config.js in deeply folders nested

### ISSUE THREAD

**Issue by jairmedeiros** [liferay/liferay-frontend-projects#822]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ x ] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Description

**Desired behavior:**
`yarn format` or `yarn checkFormat` reach the `npmscripts.config.js` configurations present in liferay-portal root.

**Current behavior:**
If a run the command in, eg. `modules/dxp/apps/osb/osb-site-initializer`, it's works. The command reach issues and fix them. But if a go to a more deeply directory, eg. `modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal`, the file config are ignored and I have a fake success.

**Other information (environment, versions etc):**

- Nodejs v16.13.1
- Fedora 34 w/ Gnome
- Liferay Portal DXP Edition

Context in Slack (https://liferay.slack.com/archives/C03CAD9EF/p1641915255001500)

**Comment by kresimir-coko** [comment]
After investigating a fair bit I found the main difference between the `yarn format`/`yarn checkFormat` calls inside those 2 folders.

When running it inside the deeper folder, it takes these [globs](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/npm-tools/packages/npm-scripts/src/config/npmscripts.config.js#L8). But, when run inside the shallower folder it takes the [liferay-portal ones](https://github.com/liferay/liferay-portal/blob/master/modules/npmscripts.config.js#L15-L25).

I have yet to figure out where the difference is defined, but this is where the local [globs](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/npm-tools/packages/npm-scripts/src/scripts/format.js#L54) are being declared

**Comment by kresimir-coko** [comment]
After investigating this further, I'm not sure if this is a real issue. @jairmedeiros Can you elaborate what you mean by _"fake success"_? Does `yarn format` complete with a success message but without fixing any formatting errors, because I can't replicate that? 

If you are using a custom config somewhere, and want `yarn format` to pick that one, can you provide me with that config, and tell me where you placed it?

Running `yarn format` from the following folders with a formatting mistake inside [osb-side-initializer-customer-portal/index.js](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/zippableResources/fragments/customer/fragments/actions-card/index.js) fixes the formatting issue in the same way, but it checks different files:
- `modules` (checks all files)
- `osb-site-initializer` (checks all files)
- `osb-site-initializer-customer-portal` (checks 6 files, the ones that are just in that module)

**Comment by jairmedeiros** [comment]
> Does `yarn format` complete with a success message but without fixing any formatting errors, because I can't replicate that?
Exactly.

> If you are using a custom config somewhere, and want yarn format to pick that one, can you provide me with that config, and tell me where you placed it?
No. I am not using a custom config.

I tried to run `yarn format` in `liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal` to find a space mistake in a file inside `extra/remote-app/src` as like you, but return a success.

But, if a run in a shallower directory like `liferay-portal/modules/dxp/apps/osb/osb-site-initializer`. It's work, fix the issues.

**Comment by kresimir-coko** [comment]
> But, if a run in a shallower directory [...]

That is intended functionality, as far as I'm aware. I, personally, always run those commands from `modules/` so it encompasses the entire repository, but I can see why the deep folders limit the amount of files they check (in my example it checked only 6 files that live inside that submodule).

The title of the issue, and to a certain extent the description were misleading. I thought it didn't pick up the configuration file and that it wasn't fixing the formatting issues. But, the issue is instead that running `yarn format` in a deep folder will only check that deep folder, not the entire repository.

I think that's the intended functionality, as nothing prevents you from running it `yarn format` in a shallow folder, but the current implementation also allows you to have a much quicker and precise `yarn format`  if you choose to run it inside the deep folder.

Correct me if I'm wrong @bryceosterhaus

**Comment by bryceosterhaus** [comment]
So we should be able to run these scripts within the modules themselves, meaning, if I am working in `frontend-js-web` I should be able to run format within that directory itself. Now the difference here is that in `liferay-portal`, when running `ant format-source`, we pick up the npmscripts.config.js from `modules`. When running within a module itself, we only use the default config (like you mentioned, @kresimir-coko).

I think the root of the issue here is that site-initializers utilize an additional directory, `extra`. Now if we look at our default config, we don't include `extra` in our globs. So I think the fix here is likely adding `extra` as a directory [here](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/npm-tools/packages/npm-scripts/src/config/npmscripts.config.js#L10), similar to dev/src/test

**Comment by kresimir-coko** [comment]
You're right @bryceosterhaus, my testing didn't include the `extra` folder, my bad.

**Assumption**: A formatting mistake is made in [site-initializer-raylife/index.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/site-initializer/site-initializer-raylife/extra/remote-app/src/index.js)

**Test:** Currently, the behaviour is such:
1) `yarn format` executed from `/site-initializer-raylife` doesn't fix the change in the file above (checks 37 files)
2) `yarn format` executed from `/modules` does fix the change in the file above

**Result:** With the changes in the PR, the 1) case checks 196 files, and does fix the formatting mistake
