### ISSUE TITLE
Check that the provided version number matches the one in package.json

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#87]
### Issue type

-   :gift: Feature request

### Description

**Desired behavior:**
I propose looking at the version number in `package.json` and, if the provided number doesn't match it, warn the user. I know this has to be heuristically checked, but if, for example, the `package.json` has `10.0.0` and the user provides `10.0.3` it is clear that it is wrong, as only `11.0.0`, `10.1.0` or `10.0.1` would make sense in such context.

**Current behavior:**
Changelog generator trusts the user provided version number blindly.

**Repro instructions (if applicable):**

**Other information (environment, versions etc):**

**Comment by wincent** [comment]
So here's the gotcha — all the projects that use the changelog generator currently use this process:

1. Run the generator with `--version=$THE_VERSION_THAT_IS_ABOUT_TO_BE_RELEASED`.
2. `git add --patch` the changes (ie. affording an opportunity for inspection, catching mistakes etc).
3. Actually commit/release (usually via `liferay-js-publish`, triggered by calling `yarn version --minor` etc).

So we can't just warn the user because _every_ release will get a warning and people will ignore it. We'd need to rework the entire workflow, and we'd have to be very thoughtful about it because I don't really want to lose the value of the manual review step (which I think is an important quality safeguard).

I mean, at least in the context of the monorepo, it will be easier for us to make a higher-level release script that takes care of everything. That could be, for example, something that gets the user to supply the next version using `--patch`, `--prepatch`, `--minor` (etc) — ie. basically the same options `yarn version` takes — and then invokes the changelog generator, gets the user to review/accept, and then invokes `yarn version`. The idea would be to discourage the manual use of `--version=` (`--new-version` in Yarn terminology), because it is possible to get it wrong. If I were going to implement this, I would probably do it in terms of a `.gitignore`-d dotfile that records the next version to be released, and the "release" script would take care of reading it and passing the value on to the subtools; that way we preserve the ability of the user to see it as a multi-step process that they can interrupt, pause, resume restart, and not a monolithic script that has to succeed entirely all at once.

**Comment by wincent** [comment]
Another thought that just occurred to me that might deliver some value without getting into the "higher-level" release script that I mentioned above.

I just shipped [some edits to these contributing guidelines](https://github.com/liferay/liferay-frontend-projects/pull/107) and it made me realize that my common workflow is usually:

1. Look at `package.json` to see current version.
2. Based on my knowledge of what changes have been merged, or from looking at `git log`, decide what next `$VERSION` should be.
3. Run `npx @liferay/changelog-generator --version=$VERSION`.

or:

1. Run `npx @liferay/changelog-generator --version=$LITERALLY_ANY_VERSION_NUMBER --dry-run` in order to see both what the current version is and what changes will be going into the next release, thus enabling me to figure out what `$VERSION` should be.
2. Run `npx @liferay/changelog-generator --version=$VERSION` for real.

Which in turn suggests that if we make a couple of tweaks to the changelog generator:

1. Teach it that when `--dry-run` is in effect, it can use a fallback `--version` value even if the user doesn't supply one.
2. Teach it how to take `--patch`, `--minor`, `--major` flags instead of `--version`.

Because then the release flow would boil down to:

1. Run `npx @liferay/changelog-generator --dry-run`; based on what you see, decide whether to make this a patch, minor or major release.
2. Run `npx @liferay/changelog-generator --minor` (etc).
3. If you like what you see, `git add -p` it.
4. Run `yarn version --minor` (etc).

We could also consider adding an `--auto` switch which would effectively do:

1. Run in `--dry-run` mode, showing the changes.
2. Prompt the user for desired release type (`minor`, `major` etc).
3. (Automatically) run again, but this time without `--dry-run` and supplying the appropriate `--major` etc switch.
4. (Automatically) `git add` the changes (possibly with a "press Y to confirm" kind of prompt).

Which would reduce the release process to:

1. Run `npx @liferay/changelog-generator --auto`
2. Run `yarn version --minor` (etc).

**Comment by wincent** [comment]
> 2\. Teach it how to take `--patch`, `--minor`, `--major` (etc) flags ~instead of~ as alternatives to `--version`.

Just as a cross-reference, this is implmented in https://github.com/liferay/liferay-frontend-projects/pull/196

**Comment by izaera** [comment]
I'm going to close this since it hasn't been a problem for quite a while (most probably because of this https://github.com/liferay/liferay-frontend-projects/issues/87#issuecomment-710052699)
