### ISSUE TITLE
React lazy loading of compontents

### ISSUE THREAD

**Issue by wsyski** [liferay/liferay-frontend-projects#904]
This is just a question. Does Liferay npm bundler v3 support React.lazy() as described in the following example:
https://www.loginradius.com/blog/engineering/lazy-loading-in-react/#:~:text=In%20essence%2C%20lazy%20loading%20means,it%20at%20the%20same%20time.

If yest does it work also for the latest version of v2
Thanks

**Comment by wsyski** [comment]
This issue is probably related to my earlier issue about Angular lazy loading:
https://github.com/liferay/liferay-frontend-projects/issues/169

**Comment by wsyski** [comment]
I have tested an examle. It worked, but not as intended. The lazy load Component was replaced with the synchronous Component load.

**Comment by wsyski** [comment]
Please find working examples:
https://github.com/wsyski/react-lazy-demo
This is a standalone react application. It works as intended with lazy loading of the LazyCalendar component
https://github.com/wsyski/react-lazy-load-portlet
This is a portlet. It works, but LazyCalendar is loaded synchronously, not lazy.

**Comment by kgkars** [comment]
There was a bug where it did not handle code splitting for React correctly that was just fixed. I didn't try the example you are showing, but when I did code splitting based on routes, it was only pulling the associated React bundle when I actually loaded each page.  (I know it worked this way, because before the bug, I would get 404 errors only on the pages that didn't have their split code bundled. :)).

**Comment by wsyski** [comment]
You are probably talking about the following fix:
https://github.com/liferay/liferay-frontend-projects/commit/d94298d3fcc16395516d3002ec75331732f4c44e
But this fix is about so called adapted react portlets. In my project I am using the js-extender and liferay js toolkit v3. Would it still work?

**Comment by kgkars** [comment]
Ahh, you are right, I was using the adapt project to convert a Create React App project to Liferay.  I'm not sure about the straight React apps generated by Liferay's toolkit. In my experience, the build tools have been more supportive in adapting a Create React App project to Liferay, largely because it let's you use Typescript templates pretty much OOTB.

**Comment by wsyski** [comment]
We are building a quite large react application. Lazy load is very essential, any hope for this feature?

**Comment by izaera** [comment]
Looking at the sample provided, I guess the key is in [this line](https://github.com/wsyski/react-lazy-demo/blob/master/src/LazyCalendar.js#L5).

The "problem" with lazy loading is that you need some way to asynchronously load modules and we don't provide anything for that in the JS Toolkit. The only way something like that could work would be replacing any dynamic `import()` construct by a call to `Liferay.Loader.require()` so that the load of the required module is really async.

We are currently investigating new ways to bundle projects using webpack and ESM externals so I would say we won't bring dynamic import to the `liferay-npm-bundler`, but wait until that webpack + ESM thing arrives to the JS Toolkit. Meanwhile, you could try using the `Liferay.Loader.require()` invocation and later (when the JS Toolkit can handle it) you can revert that to `import()`.

The only tricky part is going to be the conversion from `import("./Calendar")` to a valid `Liferay.Loader.require()` call, because it needs to contain the full canonical name of that module and that depends upon the name of the project and its version. But I guess you can encapsulate it somehow with a custom `import()`, probably.

One last caveat: `Liferay.Loader.require()` is officially an internal, not a public API, so don't spread calls to it all over your code because it is possible that some day in the future you need to change it to some other thing. Given that we are going towards ESM, I would say it would be substituted by `import()`, but I don't know yet.

Hope that helps.

**Comment by izaera** [comment]
I'm closing this as replied to avoid triaging it again, but feel free to add content or reopen it as needed.

**Comment by Betakaro** [comment]
Based on @[kgkars](https://github.com/kgkars) comments in this thread and on these docs with [bundling limitations](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-toolkit/docs/caveats/bundling.md) and [adaptation limitations](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-toolkit/docs/caveats/adaptation.md) I assumed that dynamic imports are not working just with liferay-npm-bundler approach.  

So I tried using the adaptation method for CRA (basically my code was almost same as example above https://github.com/wsyski/react-lazy-demo just without `liferay-npm-bundler`). 

When I ran it as standalone app it was working as expected. But when the app is deployed in Liferay all chunks are loaded at once on page load.

Code splitting would solve lot of troubles for our team, because now we have so big bundle, that after deploying a new version, for most users it fails on 7 second module resolution timeout. I'm aware that it can be changed in portal settings, but who would like to wait longer anyways? :)

Last question. Is the only solution trying some hacking with `Liferay.Loader.require()` or it's my fault/misunderstanding?

**Comment by izaera** [comment]
> Is the only solution trying some hacking with Liferay.Loader.require() or it's my fault/misunderstanding?

It's the only solution given the current Liferay Portal + JS Toolkit architecture. However, that doesn't mean that what you are trying is impossible to do in Liferay Portal. You can create a regular portlet, add the bootstrap JS file to its headers and then let webpack or your framework handle the load of the rest of the chunks as needed. Something similar to what adaptation does but tailored for your use case.

Some of our users have chosen not to use the JS Toolkit and hack their custom builds/deployments because they had very specific needs and they are not having any problem. In the end, the fact that the AMD loader + toolkit is used by the core of the portal doesn't prevent anyone from using other architectures in parallel.

For example: we are now slowly adding support for [browser modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) and both AMD and browser modules coexist and interop between them seamlessly :-)
