### ISSUE TITLE
Integrate liferay-npm-scripts into Liferay Learn

### ISSUE THREAD

**Issue by rdai10** [liferay/liferay-frontend-projects#91]
The [Liferay Learn project](https://github.com/liferay/liferay-learn/) would like to use `@liferay/npm-scripts` to format its source code (`scss`, `js`, `md`, `yml`, and html in the form of `jinja 2` templates).

Preliminary work has been done to incorporate the package into the Learn project, but it's only being used to format `scss` so far. There are a few bumps on the road:
- The project uses a tooling called `Sphinx` that packages jquery out of the box. In the project's javascript files, there are references to the jquery `$` that throws errors when using npm-scripts. Are there any tips for configurations that we can add to get around that? A way to avoid inlining `<!-- prettier-ignore -->` comments would be preferred.
- There is a conscious effort to organize the project into `/docs` and `/site` folders at the root to create a separation between documentation material and its [website](https://learn.liferay.com/) source. However, we do want to be able to format all the md files in the `/docs` folder from inside the `/site/homepage` folder. I ran into issues defining an appropriate glob pattern to go up the directories for my `npmscripts.config.js` file. I came across https://github.com/liferay/liferay-npm-tools/pull/141 where a custom glob library was implemented for `liferay-npm-scripts` and hope to receive some help understanding what it expects.

Let me know if I can provide any clarification that will be helpful! Thanks!

**Comment by rdai10** [comment]
@jrhoun, feel free to chime in!

**Comment by wincent** [comment]
Thanks @rdai10.

I added [one comment here](https://github.com/brianchandotcom/liferay-learn/pull/69/commits/9a208f247fd9bc25673ed726ab339c31b6cf4673#r497271170):

> You don't need the `yarn` here.
>
> You also have a couple of options if you want to roll this out more "gently".
>
> - One is to use `fix` and `check` like you are here. Those are going to run _all_ of ESLint, Prettier, stylelint, plus any additional "pre-flight" checks that `@liferay/npm-scripts` implements. This is obviously a higher barrier which may add some friction in return for more consistency/quality (at least, that's the theory).
> - The other is to use `format` and `format:check` (ie. `liferay-npm-scripts format` and `liferay-npm-scripts format:check`). This _only_ runs Prettier, so the barrier to entry is lower and it is easier to turn on this lighter-weight check, and later on tighten things up by activating the broader check.

For example, I don't think it's Prettier which is throwing the error you're talking about here:

> there are references to the jquery `$` that throws errors when using npm-scripts.

It's probably coming from ESLint. Can you share the console output so that we can analyze it and confirm that hypothesis? If it is from ESLint, we don't need/want to use `prettier-ignore` directives; we'll need to add an `.eslintrc.js` that tells ESLint about the `$` global, and then it will stop complaining about it.

> I ran into issues defining an appropriate glob pattern to go up the directories

You can't really do any `..` type stuff using Prettier or ESLint. They expect to run from a "root" (in your case, that's current `/site/homepage`) — and for example, a file like `.prettierignore` *has* to be at the root or it won't have any effect.

So, if you want to selectively format some of `/site/homepage` and some of `/docs`, you have to hoist the config up to the common ancestor (ie. the root will be `/`) and then selectively ignore the directories that you _don't_ want to check. I can help with the globs once you've done that.

---

The other thing I think we'll need to do is teach the scripts to accept `*.md` and `*.yml` globs. We have a [hard-coded list](https://github.com/liferay/liferay-frontend-projects/blob/fda8587ef8268bcf423e4adb0ae00392e754716d/projects/npm-tools/packages/npm-scripts/src/scripts/format.js#L23) of file-types that we want to support, and we started with a small/restrictive list because we wanted to roll out the tooling in a very controlled way in liferay-portal (given that so many filetypes there are already handled by the Java Source Formatter). I've created an issue for this: https://github.com/liferay/liferay-frontend-projects/issues/92

**Comment by rdai10** [comment]
@wincent 
You are correct that it's ESlint that's complaining about the jquery `$`. When I switch to running `format:check` I don't see the same errors. It appears when I run `check`.
Here is the output when executed with `check`:
```
liferay-learn/site/homepage/_static/js/page-alert.js
  27:17  error  Unexpected function expression.  prefer-arrow-callback
  43:3  error  '$' is not defined.  no-undef
  43:51  error  Unexpected function expression.  prefer-arrow-callback
  53:1  error  '$' is not defined.  no-undef
```

**Comment by wincent** [comment]
The other thing you can do if you want to turn ESLint back on is tell it that `$` is a global.

Something like this in an `.eslintrc.js` file at the root:

```js
module.exports = {
    globals: {
        $: true,
    },
};
```

If you don't want to force usage of arrow functions, you can add this too:

```js
    rules: {
        'prefer-arrow-callback': 'off',
    },
```

(The reason we prefer arrows in liferay-portal is we have Babel running over everything, which means arrow functions get safely transpiled and don't break IE.)

**Comment by rdai10** [comment]
Thanks @wincent ! I added the config at https://github.com/brianchandotcom/liferay-learn/pull/74 and everything works as expected.

**Comment by wincent** [comment]
So we just pushed [@liferay/npm-scripts v33.1.0](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv33.1.0), which includes [that PR #103 allowing it to format YAML and Markdown](https://github.com/liferay/liferay-frontend-projects/pull/103).

At this point, @rdai10, we can probably close this issue. The remaining wish-list item (formatting those Jinja2 templates which have ".html" extension) could be split into another issue — although given the cost (high) vs the relative reward (🤷‍♂️), it would probably not be something that we would be likely to prioritize in the short-term.

**Comment by rdai10** [comment]
Hey @wincent 
Thanks for working so quickly on this! I updated to the latest version [here](https://github.com/rdai10/liferay-learn/commit/2b5a5c4657e14005c3ac6a0fdf547de3555cf1f0), but when attempting to run `check`, encountered this error locally:

```
> liferay-npm-scripts check

{ Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/rebecca/projects/liferay/liferay-learn/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:30:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
```
github action also throws the same error:
![image](https://user-images.githubusercontent.com/6843719/94955659-c5379f00-049f-11eb-942f-fe35dab8d702.png)

Looks like there's unmet dependency?

**Comment by wincent** [comment]
Cool, thanks for reporting that. We use `typescript` in our `devDependencies` and that module already happens to be in liferay-portal, so it works there. This means we meed to promote it from `devDependencies` to `dependencies` to get it to work out-of-the-box in places which don't necessarily already have `typescript`. I'll do that today.

**Comment by wincent** [comment]
We just pushed https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv33.1.2 which should include the necessary `typescript` dependency.

**Comment by rdai10** [comment]
Thanks @wincent for all your help! Applied the changes at https://github.com/jrhoun/liferay-learn/pull/701 and all seems to be working!

**Comment by wincent** [comment]
Cool. Thanks for confirming @rdai10.
