### ISSUE TITLE
Clean up duplicate Jest mocks in DXP and provide them through npm-scripts

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/liferay-frontend-projects#947]
One thing we need to do is consolidate and update our Jest mocks in our npm-scripts.

If you search throughout portal for `jest-setup.config.js` files, you'll see ones that are missing in our scripts.

You can also look through our backlog on the projects repo as well as checking Slack where a handful of people bring up.

Some of the mocks are fine, we just want to reduce repeated ones. Like "sub" or "FeatureFlags".

So a first step would be consolidating a list of items to add and create an issue on our repo, and then you can close or link any previous issues about this to the new one.

It doesn't have to be perfect or all-encompassing, but hopefully, we can at least create a dent in the duplicated ones

**Comment by kresimir-coko** [comment]
@bryceosterhaus Some notes while investigating and trying to make some changes

- What do we do about defined functions that get assigned to the Liferay.Util object? Like this example of [sub](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/jest-setup.config.js#L74-L81). We should aim to remove all overrides, but teams use them for testing. Perhaps we can refactor their tests which should enable us to remove those overrides.
- Do we add the mocks that aren't duplicates but are still used in one module?

**Comment by bryceosterhaus** [comment]
I think we should aim to provide mocks for most global "Liferay" things that other teams use. So for your example of sub, I think we would want to remove their implementation and have them rely on our mock we provide in npm-scripts. And yeah, we may have to refactor their tests slightly, or update some snapshots, but we shouldn't be changing anything integral to their tests.

> Do we add the mocks that aren't duplicates but are still used in one module?

Yeah I would try to provide mocks for any global that comes from FI, meaning anything in frontend-js-web or the other modules we maintain. So if there is a mock for Liferay.SomeItemHere, and it is only used in once place, we can probably go ahead and add a mock on our side for that because we can expect it would likely be used in other places in the future.

The one thing we _don't_ want to move to our mocks is something specific to their module. So we don't want to move module-specific mocks to npm-scripts.

Also, not all modules will call it `jest-setup.config.js`, a more accurate way would be to search for `setupFiles` and `setupFilesAfterEnv` in their package.json. They may name is something different than jest-setup.

**Comment by kresimir-coko** [comment]
Alrighty, that sounds like a pretty big task then. There's a lot of Liferay.Utils that will need to be added and probably a few decent testing changes.

I'll start with the changes inside this project, and then make the changes in DXP after this side of things has been merged.

**Comment by bryceosterhaus** [comment]
@kresimir-coko sorry I think I may have miscommunicated. We don't need to add _all_ of the Utils immediately. I would only add ones that people are already mocking out.
